Update the checkout action version in all workflows
kworkflow/kworkflow pull request #1063
Opened 2024-03-27 14:25 UTC by sahil-sagwekar2652

GitHub actions using Node.js 16 are being deprecated. This also comes up as a warning in the workflow run logs. This commit updates the checkout actions version to v4 which uses Node.js 20.

I have tested the actions on my fork and they executed without any warnings.

![image](https://github.com/kworkflow/kworkflow/assets/89456541/0f137e8f-1e91-4a24-a744-b43dc3531f9f)

2024-03-27 22:11 UTC, rodrigosiqueira commented
@sahil-sagwekar2652 thanks for this PR.
Could you also update the `integration_tests.yml` file?

2024-03-28 16:16 UTC, davidbtadokoro requested changes
Great catch and pro-activeness on tackling this issue! Looks legit to me :+1: 
@rodrigosiqueira, going to wait for your green-light here.

2024-03-28 16:31 UTC, sahil-sagwekar2652 commented on .github/workflows/test_setup_and_docs.yml
> +      # This is here just because git-email cannot be installed in the
Hey @davidbtadokoro, No worries at all! I don't think this is being nitpicky, but more about maintaining the coding style and workflow. Thanks for pointing these things out as I get to learn from them.  I'll keep this in mind for future commits.

Your feedback is always appreciated, and I'm glad to have your insights.

Cheers!

2024-03-31 17:32 UTC, rodrigosiqueira commented
Thanks a lot for this PR!
Change merged into the unstable branch.

2024-03-31 17:32 UTC, closed without merging