Added --repeat option on pomodoro
kworkflow/kworkflow pull request #1086
Opened 2024-04-18 20:48 UTC by th-duvanel

`kw pomodoro --repeat`allows the user to repeat the last pomodoro argument commands used by him, without having to type it all over again.

2024-05-17 22:30 UTC, th-duvanel commented
Just to make a checkpoint about my progress: I exchanged some emails with @davidbtadokoro about the PR. After the next week, I will focus more on the PR and the recommendations given by him.

This PR will be finished soon. Thanks for the patience!

2024-05-20 16:40 UTC, rodrigosiqueira requested changes
Hi @th-duvanel ,
First of all, thanks a lot for this PR, and I am sorry for my huge delay in providing feedback.

Anyway, I believe the best way to implement this feature is to check the latest Pomodoro in the database instead of creating a temporary file. All of this information is stored in the SQLite database. I gues @davidbtadokoro can help you with that.

Also, squash the second commit into the first one.

2024-05-21 10:44 UTC, davidbtadokoro commented
Hi @rodrigosiqueira. Just to update you, I had a couple of offline discussions with @th-duvanel, and we formulated a good direction for him to implement this using the latest session in the DB. Thiago already has a good looking draft, and he communicated to me that he will be able to work on it soon.

2024-05-29 18:30 UTC, th-duvanel commented
Hello!
Sorry for the delay, things were a bit more complicated than I thought! After some conversation (and coding) with @davidbtadokoro and the suggestions from @rodrigosiqueira, we made it to this commit.
We used the database to fetch the last session, added some autocompletions for the new function, added some tests and its documentation. It's all squashed in one commit. Any change you guys would recommend, I'm open to it.
Thanks for the help and patient this far.

2024-05-31 14:08 UTC, rodrigosiqueira requested changes
Very nice improvement!

2024-05-31 14:08 UTC, rodrigosiqueira commented on tests/unit/pomodoro_test.sh
> +function test_fetch_last_pomodoro_session()
Create one test that validates the condition that we don't have any previous session, and the user tries to use this option. Use a new test function for that.

2024-05-31 14:08 UTC, rodrigosiqueira commented on tests/unit/pomodoro_test.sh
> +  compare_command_sequence 'Older session' "$LINENO" 'expected' "$output"
Let's add a little bit of entropy between these tests, create some new entries between the sessions, and ensure that the `--repeat` will get the new session with different parameters (time, tag, and description).

2024-05-31 14:08 UTC, rodrigosiqueira commented on src/pomodoro.sh
> +  say "- Duration: ${options_values['TIMER']}"
I don't think that showing the session in seconds is a user-friendly approach. You can improve this output by handling it on a correct scale. For example, if it has less than 60 seconds, use seconds; if it has less than 60 minutes, keep it under minutes, and so on.

2024-05-31 15:14 UTC, th-duvanel commented on documentation/man/features/kw-pomodoro.rst
> +| *kw* (*p* | *pomodoro*) (-r | \--repeat) [\--verbose]
I can implement this in the future. Probably it won't be hard, but more "errors" will appear, like the ones pointed out by you in the requested changes, so I prefer to wait for the next opportunity.

2024-06-04 13:15 UTC, th-duvanel commented on src/pomodoro.sh
> +        shift
Just adding an update: me and @davidbtadokoro talked about the implementation recommended by you and he clarified your description of the "problem". No worries, I will update the commit and soon as possible.

2024-06-08 15:16 UTC, rodrigosiqueira requested changes

2024-06-08 15:16 UTC, rodrigosiqueira commented on documentation/man/features/kw-pomodoro.rst
> +| *kw* (*p* | *pomodoro*) (-r | \--repeat) [\--verbose]
Ok, but let's update this to `--repeat-previous` or similar.

2024-06-08 15:16 UTC, rodrigosiqueira commented on src/pomodoro.sh
> +
Could you address this comment?

2024-06-08 18:52 UTC, th-duvanel commented
Hey @rodrigosiqueira, for some reason the changes I've made didn't apply to the new commits. I'm sorry for this, I made the changes you requested more than a week ago. I think we are good now, tell me what you think about the changes.

2024-06-20 10:45 UTC, davidbtadokoro commented
Hi @th-duvanel, and thanks for the great improvement on this PR and continuous work! There were some comments that I felt I could incorporate myself, which I communicated to you offline, so merged into unstable branch :+1:

2024-06-20 10:45 UTC, closed without merging