tests: integration: build_test: add the kw build test
kworkflow/kworkflow pull request #1087
Opened 2024-04-19 15:58 UTC by aquilamacedo

Introduce default integration tests for kw build across Debian, Archlinux and Fedora

2024-04-27 15:01 UTC, rodrigosiqueira requested changes

2024-04-27 15:01 UTC, rodrigosiqueira commented on tests/integration/build_test.sh
> +
I really think we should start to use `setUp` and `tearDown` helpers. All the code here looks like a setup.

2024-05-08 18:03 UTC, rodrigosiqueira commented
@aquilamacedo could you update this PR?

2024-05-08 18:07 UTC, aquilamacedo commented
> @aquilamacedo could you update this PR?

Hi @rodrigosiqueira. Yes, I'll update.

Can you look at my latest pull request  (#1108)? 

That will influence the update of this one.

2024-05-21 22:22 UTC, closed without merging