Fixes order parameter in assert_equals_helper
kworkflow/kworkflow pull request #1092
Opened 2024-04-21 13:52 UTC by auyer

The order of arguments in `assert_equals_helper` is declared in docs and used in one way, but defined in another way

Definition in `codingstyle.rst`
```rst
   assert_equals_helper "$error_message" "($LINENO)" "$output" "$expected_output"

or::

   assertEquals "($LINENO)" "$output" "$expected_output"

```

I introduced a fake error to demonstrate this in the `mail_test.sh` file.

```bash
parse_mail_options '--to=some@mail.com'
expected='intentional-error@demo.com'
assert_equals_helper 'Set to flag' "$LINENO" "${options_values['TO']}" "$expected"
```

Expected Result:
```bash
./run_tests.sh test mail                               
...
test_mail_parser
ASSERT: line 324: Set to flag
  Expected Result: intentional-error@demo.com
    Actual Result: some@mail.com
```

Result before my patch:
```bash
./run_tests.sh test mail                               
...
ASSERT: line 324: Set to flag
  Expected Result: some@mail.com
    Actual Result: intentional-error@demo.com
```

Fixes #1091

2024-04-25 11:22 UTC, davidbtadokoro commented
Hi @auyer, and sorry for the delay. Nice catch and proactiveness in solving the matter. However, I think that we should use a different approach to solve this. See the comment that I left in the issue for the explanation.

2024-04-25 11:36 UTC, auyer commented
I had the impression that the order ` "$output" "$expected_output"` was used everywhere. 
But I just found examples using the opposite, like you mentioned.

 will check what order is used more, and modify the others. Ok ?

2024-04-25 11:53 UTC, davidbtadokoro commented
> I had the impression that the order ` "$output" "$expected_output"` was used everywhere. But I just found examples using the opposite, like you mentioned.
> 
> will check what order is used more, and modify the others. Ok ?

I can't assure you that `expected` at 3 and `output` at 4 is the most used, but I think it is best just to update the wrong usages (i.e., where expected is 4 and output is 3, invert). My interpretation is that the use isn't standardized, so we should enforce the correct, not the most used, which, in my opinion, is `expected` at 3 and `output` at 4 (it makes more sense to me).

Also, if you want to tackle this issue, I think is best to either open one PR with one commit for each test file correction, or one PR for each file correction (I think this is best, as we can do it more incrementally and agile).

2024-04-26 02:12 UTC, auyer commented
I did not fix every file, but I got most of them.
There are two files I tried to fix, but `shellcheck` started complaining about unrelated issues I wont fix now.

2024-04-27 15:04 UTC, rodrigosiqueira commented
Hi @auyer ,
This is a very nice clean-up!
I think all of these commits could be squashed into a single one with a good commit message.

2024-04-27 20:31 UTC, auyer commented
Hi @rodrigosiqueira. I just squashed them all, as you requested.

2024-04-28 14:01 UTC, davidbtadokoro requested changes
Hi @auyer, and thanks again for the change!

@rodrigosiqueira, actually, I was the one that prompted auyer to split the changes into dedicated commits for each test file :sweat_smile:. I thought it would make it more organized, but as these are clean replaces, I get why it is better to squash them (sorry @auyer :smiling_face_with_tear:).

In any case, the PR looks legit to me. The only are about the commit message. Change the subject to follow the pattern `target: file: Do something`. As the fixing the wrong usage of `assert_equals_helper` test suites is the primarily goal, I think it makes sense for the subject to be something like `tests: unit: Fix usage of <...>`.

2024-04-28 14:11 UTC, auyer commented
@davidbtadokoro  Your subject suggestion wold better fit a 1commit/file situation. Nevertheless, I adapted the subject to match your request.

2024-04-28 17:31 UTC, davidbtadokoro commented
> @davidbtadokoro Your subject suggestion would better fit a 1commit/file situation. Nevertheless, I adapted the subject to match your request.

I get that as you are also changing the documentation, there doesn't seem to be a clear subject to encapsulate every specific change. But mind that it isn't rare (I would say it is fairly common) to have a commit that directly or collaterally changes more than one file, so you should find a broader subject that conveys the overarching context in these cases without using subheads and such. Personally I would prefer a subject that focus on the fixing of the test suites and a body that mentions the change in the documentation as collateral, but this may be a matter of style.

In any case, I think the subhead in the subject isn't great and you can avoid using it, like

```
tests: unit: fix reverse argument order of assert_equals_helper in docs and test cases
```

instead of

```
tests: unit: fix docs and usage of assert_equals_helper - argument order is reversed
```

Notice that you are maybe trying to explain too much in the subject, which you can use the body for that.

(Obs.: This may seem like nitpick territory, but commit messages are almost as important as the changes itself).

2024-05-03 13:49 UTC, davidbtadokoro commented
Hi @auyer, and thanks again for the (many) updates! Everything looked legit, and with the adjustment on the commit message, I feel like we are good. Merged into the unstable branch :+1:

2024-05-03 13:49 UTC, closed without merging