Added comments on returns that didnt have errno error codes
kworkflow/kworkflow pull request #1112
Opened 2024-05-09 23:51 UTC by BrunoRLevi

2024-05-10 16:25 UTC, rodrigosiqueira requested changes
lgtm, just update the commit message.

2024-05-10 16:25 UTC, rodrigosiqueira commented on database/migrate_legacy_data_20220101.sh
Please, update your commit message to follow the kw pattern. Also, add a descriptive message.

2024-05-11 16:43 UTC, BrunoRLevi commented on database/migrate_legacy_data_20220101.sh
I updated the commit message and added a description, let me know if these are alright or if more changes are needed.

2024-05-12 01:03 UTC, davidbtadokoro commented on database/migrate_legacy_data_20220101.sh
Hi @BrunoRLevi.

The commit message Siqueira alluded is the actual commit message. Note that if you go to the tab `Commits` at the top of this PR, the actual commit message is the same, as you've just changed it in the PR UI of GitHub. You will have to use `git commit --amend` to change the commit message and use `git push --force` to update the PR. 

## Commit message review

In any case, I think the commit subject message is OK, but remove space before `:`, and use `add` instead of `added`, as commit subject messages should have the imperative form like **Do**.

Also, don't forget to add a `Co-developed-by` tag for Lucas.

2024-05-12 01:48 UTC, BrunoRLevi commented on database/migrate_legacy_data_20220101.sh
Done! By the way, when doing lots of changes, do I just specify the directory where most changes happened? I started the commit message with "src", but there were also changes in kw and run_tests.sh and setup.sh.

2024-05-12 02:43 UTC, davidbtadokoro commented on database/migrate_legacy_data_20220101.sh
Hi @BrunoRLevi, and thanks for the quick update!

> By the way, when doing lots of changes, do I just specify the directory where most changes happened? I started the commit message with "src", but there were also changes in kw and run_tests.sh and setup.sh.

Hmm, now that you've noted this I think you don't need the prefix `src:` indeed, as you are making a change project-wise.

Also, you forgot to add the commit message body from the PR to your actual commit.

2024-05-12 03:10 UTC, BrunoRLevi commented on database/migrate_legacy_data_20220101.sh
I added the commit message body to the actual commit now, let me know if any more changes are needed

2024-05-12 03:37 UTC, closed without merging

2024-05-12 03:37 UTC, davidbtadokoro commented
Hi guys, and thank you so much for the change and the quick-updates! Everything looks legit to me, so merged into the unstable branch :+1: