tests: integration: kw_ssh_test: Add integration tests for kw ssh functionality
kworkflow/kworkflow pull request #1116
Opened 2024-05-21 21:37 UTC by aquilamacedo

This pull request introduces a comprehensive set of integration tests for the kw ssh functionality. The new tests cover various features, including establishing SSH connections, transferring files, and configuring remote environments across different distributions (Debian, Archlinux, and Fedora). Additionally, several utility functions and configuration scripts were added or updated to support these tests.

2024-06-19 18:20 UTC, davidbtadokoro requested changes
Hi @aquilamacedo, thanks a lot for this PR, and sorry for this HUGE delay :sweat_smile: 

I left some general comments, but it seems that the overall structure is legit, and we will use next review cycles to make it more robust. I've encountered a consistent fail in the setup of the SSH server for the Fedora container, as you can see in the print below. In any case, thanks again for expanding the integration tests suite :+1: 

![2024-06-19-150320_1494x508_scrot](https://github.com/kworkflow/kworkflow/assets/95055784/ce422fda-dd7a-453a-840a-22260f9a267d)

2024-06-19 18:20 UTC, davidbtadokoro commented on tests/integration/kw_ssh_test.sh
> +    say "Configuring ssh server for ${distro}..."
I think we can suppress "OK output" when everything is going as expected to not pollute the test suite. IMHO, a polluted test suite output has a feeling of fail. Makes sense?

2024-06-19 18:20 UTC, davidbtadokoro commented on tests/integration/kw_ssh_test.sh
> +      success 'Done'
Following the above comment, I think we can suppress this.

2024-06-19 18:20 UTC, davidbtadokoro commented on tests/integration/podman/scripts/setup_ssh_env.sh
> +  local containers_config_file="${containers_config_dir}/containers.conf"
Is this variable being used?

2024-06-19 18:20 UTC, davidbtadokoro commented on tests/integration/podman/scripts/setup_ssh_env.sh
> +  printf 'Ensuring /usr/sbin is in the PATH...\n'
Following my comments about "OK output", this also applies her (unless these are stored in a log file of sorts).

2024-06-19 18:20 UTC, davidbtadokoro commented on tests/integration/podman/scripts/setup_ssh_env.sh
> +  printf 'Generating SSH keys...\n'
The same as the above comment

2024-06-19 18:20 UTC, davidbtadokoro commented on tests/integration/podman/scripts/setup_ssh_env.sh
> +  printf "Building and running SSH server container %s...\n" "$ssh_container_name"
The same as the above comment

2024-06-19 18:20 UTC, davidbtadokoro commented on tests/integration/podman/scripts/setup_ssh_env.sh
Sorry if I am remembering this wrong, but didn't Siqueira made a good argument about incorporating this script inside the `kw_ssh_test.sh`? I think it makes sense, as it will easier for readers to find the setup happening. If I am mistaken, ignore this.

2024-06-19 18:20 UTC, davidbtadokoro commented on tests/integration/utils.sh
> +    complain "$cmd"
This is a good change, but I think it doesn't pertain to this PR scope

2024-06-19 18:20 UTC, davidbtadokoro commented on tests/integration/utils.sh
Maybe move this commit to before the previous, as it seems that without it the last commit will have failing tests.

2024-07-13 17:25 UTC, aquilamacedo commented
Hi @davidbtadokoro. I made some improvements in this PR, can you review it? thx :)

2024-07-20 15:04 UTC, rodrigosiqueira commented
@aquilamacedo, could you rebase your change against the latest unstable branch?

2024-07-23 09:34 UTC, aquilamacedo commented
Hi @rodrigosiqueira, done!

2025-02-17 18:26 UTC, rodrigosiqueira commented
Hi,
Nobody has reviewed this change for a long time, and I have also not heard anything about this PR author. I'll close it for now. If you want to reopen the PR, we can resume the conversation in the future.

2025-02-17 18:26 UTC, closed without merging