tests: unit: maintainers_test: Add failing tests
kworkflow/kworkflow pull request #1118
Opened 2024-05-23 23:52 UTC by Lincoln-Yuji

The kw 'maintainers' feature lacks tests for its multiple corner cases where it should fail. Adding such tests ensures a larger test coverage for expected behaviors of this feature, possibly preventing future accidental undesirable changes.

2024-05-27 17:03 UTC, rodrigosiqueira requested changes
Hi @Lincoln-Yuji ,
Thanks for this PR, I added some minor comments. Btw, this test is very old and probably requires some code refactor (e.g., split tests in small functions) and code style adjustment. Additionally, you can check the coverage report to see which part of the code has not been tested yet:

https://app.codecov.io/gh/kworkflow/kworkflow/blob/unstable/src%2Fmaintainers.sh

2024-06-08 13:41 UTC, rodrigosiqueira requested changes

2024-06-08 13:41 UTC, rodrigosiqueira commented on tests/unit/maintainers_test.sh
> +  mkdir -p "$SHUNIT_TMPDIR"
https://kworkflow.org/content/codingstyle.html#avoid-short-options

Also, before every rm command, we must check if the variable is not empty or pointing to a weird path. This is very important to keep the code safe and avoid catastrophic removals. Check the function is_safe_path_to_remove.

Also, I know the old code just uses rm, but that is legacy code with some bad practices, and it must be updated.

2024-06-08 13:41 UTC, rodrigosiqueira commented on tests/unit/maintainers_test.sh
> +  mkdir -p "$SHUNIT_TMPDIR"
Maybe this should be in the tearDown function, and we cleanup everything per test.

2024-06-08 13:41 UTC, rodrigosiqueira commented on tests/unit/maintainers_test.sh
> +  }
Maybe you can move this `cd` to a specific folder to the `setUp` function and go back to the `tearDown` function; that way, each test can be simplified.

2024-06-08 13:41 UTC, rodrigosiqueira commented on tests/unit/maintainers_test.sh
> +  msg="$(maintainers_main --update-patch 'fs/some_file')"
Declare this variable as local.
Also, use a more intuitive name, something like output_from_function_xpto...

P.S.: Please review this entire commit with this comment in mind.

2024-06-08 13:42 UTC, rodrigosiqueira commented
> Hello, @rodrigosiqueira we have finished applying your requested changes and we are now waiting for new feedbacks. Thank you very much for reviewing our code and suggesting some changes.
> 
> Regarding the string concatenation style for `LINENO`, we ended up applying it for all occurences of this pattern in this file, not only the new lines we made. We did this to keep it consistent accross the entire file.
> 
> However, we had some issues adding quotes to this line:
> 
> ```shell
> cp -f tests/unit/samples/update_patch_test{_model,}{,2}.patch "$FAKE_KERNEL"/
> ```
> 
> It seems that adding either single or double quotes makes this command not copy the patch files and we are not sure if this expression is expanded by the shell itself or if the `cp` command handles this format.
> 
> Because of that we decided to only add the quotes to the new line we made and leave the others untouched.

Hi @Lincoln-Yuji , ignore my comment about cp.

2024-06-12 00:22 UTC, Lincoln-Yuji commented
Hi @rodrigosiqueira, we've finished applying your new suggestions and we hope everything is fine now. Thank you for the feedback

2024-06-13 23:59 UTC, rodrigosiqueira commented
Thanks! Change merged into the unstable branch.

2024-06-13 23:59 UTC, closed without merging