src: plugins: kernel_install: utils: Option to continue kernel deployment even with errors on mkinitcpio execution
kworkflow/kworkflow pull request #1129
Opened 2024-06-04 13:18 UTC by BLBispo

Kw deploy stops when it encounters errors that do not compromised the image. This enhancement provides  an option to continue if the error does not compromised the image.

Issue: #1083

Signed-off by: Bruna Bispo <blbispo1@gmail.com>

2024-06-08 13:00 UTC, rodrigosiqueira requested changes

2024-06-15 14:26 UTC, rodrigosiqueira requested changes
Hi,
I added some comments; please also add tests to your change.

2024-06-15 14:26 UTC, rodrigosiqueira commented on src/plugins/kernel_install/utils.sh
> +        if test -f "/boot/initramfs-${name}.img"; then
Use `[[ ]]` instead of `test`.

2024-06-15 14:26 UTC, rodrigosiqueira commented on src/plugins/kernel_install/utils.sh
> +          if [[ $(ask_yN 'Would you like to continue anyway?') == 0 ]]; then
A a new line between these two lines.

2024-06-15 14:26 UTC, rodrigosiqueira commented on src/plugins/kernel_install/utils.sh
Please wrap your commit message between 72 characters.

2024-06-15 14:26 UTC, rodrigosiqueira commented on src/plugins/kernel_install/utils.sh
> +          if [[ $(ask_yN 'Would you like to continue anyway?') == 0 ]]; then
Add a message before this question to let the user know which ERROR happened.

2024-06-15 14:26 UTC, rodrigosiqueira commented on src/plugins/kernel_install/utils.sh
> +            exit "$ret"
you can return `ECANCELED` here.

2024-06-28 15:53 UTC, rodrigosiqueira requested changes

2024-06-28 15:53 UTC, rodrigosiqueira commented on src/plugins/kernel_install/utils.sh
I don't think you address this comment.

2024-06-28 15:53 UTC, rodrigosiqueira commented on src/plugins/kernel_install/utils.sh
> +          printf "%s\n" "$output" | grep -E 'ERROR'
https://kworkflow.org/content/codingstyle.html#avoid-short-options

2024-06-28 15:53 UTC, rodrigosiqueira commented on tests/unit/plugins/kernel_install/utils_test.sh
> +  name=$(uname -r)
`uname -r` in the test will make it fragile since it will get this information from the host. Just hardcode the name.

2024-06-28 15:53 UTC, rodrigosiqueira commented on tests/unit/plugins/kernel_install/utils_test.sh
> +  local initramfspath="test/boot/initramfs-$name.img"
https://kworkflow.org/content/codingstyle.html#string-concatenation

2024-06-28 15:53 UTC, rodrigosiqueira commented on tests/unit/plugins/kernel_install/utils_test.sh
> +}
This test looks weird. Could you create one test that says no to the question and validate the exit (125)? You can also create another test that says yes and validate the other behavior.

2024-06-28 15:53 UTC, rodrigosiqueira commented on src/plugins/kernel_install/utils.sh
> +        exit "$ret"
Could you add a comment in front of each `else` that points to the `if` associated with it?

2024-07-05 17:39 UTC, rodrigosiqueira commented
@melissawen, could you check if this solution addresses your issue?

2024-07-05 19:32 UTC, melissawen commented
I'll give a try this weekend. Reading the code it seems I'll be asked to continue in case of error, can I have a option like `kw d --force` instead? Or both approaches at least?

2024-07-12 17:13 UTC, rodrigosiqueira commented
> I'll give a try this weekend. AFAIU I'll be asked to continue in case of error, can I have an option like `kw d --force` instead? Or both approaches at least?

I agree with the force option.

2024-07-27 16:59 UTC, rodrigosiqueira commented
The PR has been closed due to a lack of activity. If you have any updates, feel free to open a new PR.

2024-07-27 16:59 UTC, closed without merging