src: plugins: subsystems: drm: show current resolution and refresh rate
kworkflow/kworkflow pull request #1137
Opened 2024-06-11 12:06 UTC by viniciusfl

Solves [issue 1097](https://github.com/kworkflow/kworkflow/issues/1097).

2024-06-11 12:06 UTC, viniciusfl commented
@rodrigosiqueira @davidbtadokoro

2024-06-12 13:07 UTC, rodrigosiqueira requested changes
Hi,
Thanks for this PR; I added some comments. Also, your feature does not work as expected for remote machines or even for local machines since it is expected to be executed as root, which is not correct.

2024-06-12 13:07 UTC, rodrigosiqueira commented on src/plugins/subsystems/drm/drm.sh
> +        if [[ $line =~ $regex ]]; then
Add double-quotes around those bash variables.

2024-06-12 13:07 UTC, rodrigosiqueira commented on src/plugins/subsystems/drm/drm.sh
> +          resolution=$(sed -n 's/.*"\(.*\)".*/\1/p' <<< "${BASH_REMATCH[0]}")
Add a simple comment before your sed that describes (i.e., add an example) what kind of output we expected for `BASH_REMATCH`.

2024-06-12 13:07 UTC, rodrigosiqueira commented on src/plugins/subsystems/drm/drm.sh
> +      if [[ $line == "$resolution" ]]; then
double quotes around $line

2024-06-12 13:07 UTC, rodrigosiqueira commented on src/plugins/subsystems/drm/drm.sh
> +          hz=$(awk -F': ' '{print $3}' <<< "${BASH_REMATCH[0]}")
by hz, I think you mean refresh_rate.

2024-06-12 13:07 UTC, rodrigosiqueira commented on tests/unit/drm_plugin_test.sh
> +function mk_fake_sys_kernel_debug_dri()
This function can be useful in other tests; move it to tests/unit/utils.sh.

2024-06-12 13:07 UTC, rodrigosiqueira commented on tests/unit/drm_plugin_test.sh
> +    "128")
use single quotes.

2024-06-12 13:07 UTC, rodrigosiqueira commented on tests/unit/drm_plugin_test.sh
> +    mkdir -p "${FAKE_DRI_SYSFS}/${dir}"
avoid short options.

2024-06-12 13:07 UTC, rodrigosiqueira commented on tests/unit/drm_plugin_test.sh
> +  declare -a expected_output=(
Replace all double quotes with single quotes where we don't have a bash variable.

2024-06-13 13:24 UTC, cmhpedro commented
> Hi, Thanks for this PR; I added some comments. Also, your feature does not work as expected for remote machines or even for local machines since it is expected to be executed as root, which is not correct.

Hi! Thanks for the response. We are accessing a kernel file, that needs `sudo` permission. The expected way is executing `kw ...` and requesting `sudo` permission (similar to `setup`)? If this is not the way, is there a suggestion on how to do it?

2024-06-28 15:38 UTC, rodrigosiqueira commented
> > Hi, Thanks for this PR; I added some comments. Also, your feature does not work as expected for remote machines or even for local machines since it is expected to be executed as root, which is not correct.
> 
> Hi! Thanks for the response. We are accessing a kernel file, that needs `sudo` permission. The expected way is executing `kw ...` and requesting `sudo` permission (similar to `setup`)? If this is not the way, is there a suggestion on how to do it?

You don't need sudo to deploy to remote since it runs as root.

Also, are there any updates to my other comments?

2024-07-05 17:23 UTC, rodrigosiqueira commented
Closed due to the lack of activity.

2024-07-05 17:23 UTC, closed without merging