src: create build_and_deploy file
kworkflow/kworkflow pull request #1138
Opened 2024-06-11 12:12 UTC by BrizaMel

Create build_and_deploy utilitary. 

!1120

2024-06-11 22:03 UTC, rodrigosiqueira requested changes

2024-06-11 22:03 UTC, rodrigosiqueira commented on kw
Please, add a commit message.

2024-06-11 22:03 UTC, rodrigosiqueira commented on src/build_and_deploy.sh
> +# The `build_and_deploy.sh` file centralizes functions related to kw bd.
Maybe something like [..] file handles the sequence build followed by deploy.

2024-06-11 22:03 UTC, rodrigosiqueira commented on src/build_and_deploy.sh
> +#
Drop this extra comment

2024-06-11 22:03 UTC, rodrigosiqueira commented on src/build_and_deploy.sh
> +
drop this extra line

2024-06-11 22:03 UTC, rodrigosiqueira commented on src/build_and_deploy.sh
> +  build_kernel_main && deploy_main 1 "$raw_options"
It is better to call each function, check the return type, and then execute the next function.

2024-06-19 19:03 UTC, davidbtadokoro requested changes
Hi @BrizaMel and @lorenzoberts, and thanks for the initiative on extracting `kw bd` to a dedicated file.

I've left some inline comments, so please see if you can address them. There are also two comments that I that don't fit in the inline review:

1. As you are essentially adding a "new feature", you need to add a manpage, new completions, and an authorship of the new feature. See this PR #1121 from Lincoln, Luiza, and Sabrina for reference (pay attention the modifications in the `documentation` dir, and `src/_kw` and `src/bash_autocompletion.sh` files).
2. I think you can modify the commit message to express this adding of a "new feature", and explain the motivation in creating a dedicated file/feature for `kw bd` (again, I think the PR mentioned is a good reference).

@rodrigosiqueira, as a last discussion, how do we feel about the name `kw bd`? I think it can be easily mistaken with `kw db`, and maybe we have an opportunity to create a more expressive name with this PR.

**UPDATE 1:**

I remembered that `kw bd` completions are already implemented, so you don't need to change them. However, in case we change the feature name, you will need to change these files indeed.

**UPDATE 2:**

Also, I've tested the feature, and we need to use `include "${KW_LIB_DIR}/lib/kwio.sh"` for running kw outside the repository, and we will need to use `$@` instead of `$raw_options` as the deploy will fail, otherwise. Both problems are illustrated in the print below.

![2024-06-19-160846_899x412_scrot](https://github.com/kworkflow/kworkflow/assets/95055784/50f9a83a-da25-4200-8734-a33c8569f3b4)

2024-06-22 00:30 UTC, lorenzoberts commented
Hello @davidbtadokoro, thanks for the comments. We tried to address them all, see what you think.
We didn't know if we were supposed to consider ourselves the authors of kw bd since we are just creating its file and man page. Let us know if we should change `documentation/conf.py`

2024-06-28 15:36 UTC, rodrigosiqueira requested changes

2024-06-28 15:36 UTC, rodrigosiqueira commented on documentation/man/features/kw-bd.rst
> +which deploys the kernel.
Maybe something more direct like:

Kw bd is expected to run inside a kernel tree. It executes the build, and if there are no errors, it proceeds with deploying the new kernel.

2024-06-28 15:36 UTC, rodrigosiqueira commented on documentation/man/features/kw-bd.rst
> +along with kw bd will be redirected to kw deploy.
The first phrase contradicts the second phrase.

2024-06-28 15:36 UTC, rodrigosiqueira commented on documentation/man/features/kw-bd.rst
> +Currently kw bd does not support any options for itself.
you don't need this if there is no option.

2024-06-28 15:36 UTC, rodrigosiqueira commented on documentation/man/features/kw-bd.rst
> +	kw bd --create-package
Again, this contradicts the information you provided above.

2024-06-28 15:36 UTC, rodrigosiqueira commented on src/build_and_deploy.sh
> +  deploy_main 1 "$@"
Add a new line after the `fi` part. Also, add a comment that explains what  `1` parameter means.

2024-06-28 15:36 UTC, rodrigosiqueira commented on src/build_and_deploy.sh
> +    complain '%s\n' 'kernel build failed'
You don't need to use  `%s` in this context, you can just add the string directly in the first parameter.

2024-06-28 15:36 UTC, rodrigosiqueira commented on src/build_and_deploy.sh
> +    complain '%s\n' 'kernel deploy failed'
You don't need to use %s in this context, you can just add the string directly in the first parameter.

2024-06-28 15:36 UTC, rodrigosiqueira commented on src/build_and_deploy.sh
> +    include "$KW_LIB_DIR/help.sh"
https://kworkflow.org/content/codingstyle.html#string-concatenation

2024-07-11 01:16 UTC, rodrigosiqueira commented
Thanks for the improvements! Change merged into the unstable branch.

2024-07-11 01:16 UTC, closed without merging