src: pomodoro: create pomodoro timer with no tag specified
kworkflow/kworkflow pull request #1157
Opened 2024-08-14 19:20 UTC by gabrielsrd

This commit modifies the pomodoro.sh script to allow the registration of a Pomodoro timer without requiring a specified tag. If no tag is provided, the timer is now automatically registered with the default tag NO-TAG.

Solves: #1156

 Signed-off-by: gabrielsrd <gabrielalves@usp.br>

2024-08-16 01:41 UTC, rodrigosiqueira requested changes
Hi @gabrielsrd ,
Overall, this change lgtm. Could you just add a commit message?

2024-08-23 16:42 UTC, rodrigosiqueira commented
@gabrielsrd any update here?

2024-08-28 17:54 UTC, gabrielsrd commented
Hello, sorry for answering late. I have added the commit message.

2024-09-09 14:53 UTC, rodrigosiqueira commented
Thanks! Change merged into the unstable branch.

2024-09-09 14:53 UTC, closed without merging