Tests refactor
kworkflow/kworkflow pull request #205
Opened 2021-03-20 21:07 UTC by rodrigosiqueira

2021-03-28 21:30 UTC, melissawen requested changes
Hello @rodrigosiqueira,
I found some issues with VM deployment. Please see inline comments.
I have also verified that VM deployment on Debian and Arch works correctly after the changes attached here.
[PR205_patch.txt](https://github.com/kworkflow/kworkflow/files/6218105/PR205_patch.txt)
Thanks :)

2021-03-28 21:30 UTC, melissawen commented on src/plugins/kernel_install/utils.sh
> +  local mkdir_grub=": mkdir-p /boot/grub"
I checked that lines 188 and 203 switched places. If we assume Debian as a default option, we will use the variable mkdir_init as defined in line 203. In the arch case, we use the mkdir_grub.

2021-03-28 21:30 UTC, melissawen commented on src/plugins/kernel_install/arch.sh
> +  local cmd_grub='grub-mkconfig -o /boot/grub/grub.cfg'
It is not needed here. cmd_grub should not be passed to update_boot_loader and we also define it inside the update_boot_loader.

2021-03-28 21:30 UTC, melissawen commented on src/plugins/kernel_install/arch.sh
> +  update_boot_loader "$name" 'arch' "$target" "$cmd_grub" "$cmd_init" "$setup_grub" "$grub_install"  "$flag"
Here, cmd_grub should be removed, ie: update_boot_loader "$name" 'arch' "$target" "$cmd_init" "$setup_grub" "$grub_install"  "$flag"

2021-04-18 20:24 UTC, rodrigosiqueira commented
This patch was a draft, and I already applied most of the changes available here.

2021-04-18 20:24 UTC, closed without merging