Breakdown the help command per feature
kworkflow/kworkflow pull request #213
Opened 2021-03-31 02:27 UTC by alan-barzilay

This PR breaks down the main help function, now it works in a similar manner to the help command in git.

I also updated the kw help to include all sub-commands that were missing, but they still need a one line description each. Since I'm new to the project I don't feel confident in my ability to create an appropriate description for all these sub-commands, but nevertheless I tried to do a few of them based on the man page and my understanding of them:
```
    "\tboot,bo - TODO\n" \
    "\tbuild|b - Build kernel\n" \
    "\tconfigm,g - TODO\n" \
    "\tdeploy,d -  Install current kernel version in target machine \n" \
    "\tdiff,df - Wrapper to some useful usage of diff command\n" \
    "\tdrm - TODO \n" \
    "\texplore,e - TODO\n" \
    "\tssh,s - Ssh into any machine reachable via the network\n" \
    "\tstatistics - Show kw usage statistics \n" \
```

Closes #180

2021-04-04 16:09 UTC, rodrigosiqueira requested changes
Hi @alan-barzilay ,

First of all, thanks a lot for your patch! Your patch is a huge step to make kw more user-friendly. I really appreciate your effort in this area.

I recommend you to see my review per commit instead of seeing all the comments together. However, I have some suggestions:
1. Make your series focused only on adding and improving the helper functions. Do not add sidequests to your series.
2. Keep each helper function per file. For example, instead of adding the statistics_help() in the help.sh, add it to statistics.sh and avoid one extra include. This makes much more sense because we want to keep each functionality isolated in the specific file. Let's keep the help.sh file only for the overall command summary and for other function helpers.
3. Take care in the way that you split your commits. Make commits per functionalities; in other words, your series can be summarized in two or three commits. Maybe one commit for prepare the ground and another commit that add the helper function per file.
4. I think your series added commits from other changes, make sure that you do not add unnecessary commits in your PR. I recommend you create a new branch based on the latest code from the unstable branch per feature.
5. Do not handle --help in the same way as -h. In your series, just use `-h`; I want to use the same approach that git has for the documentation. Usually, git use --help to open the man page for the specific feature; try git add -h and git add --help. P.s.: You don't need to handle --help, only -h.

I'm looking forward for your new series :)

2021-04-04 23:39 UTC, alan-barzilay commented on src/help.sh
> +    "\tboot,bo - TODO\n" \
I see, I didn't know. Maybe we should open an issue about removing it? I though that this option was still supported, I even opened an issue about adding it to the documentation  #214 haha If there is already an issue, I couldn't find it.

2021-04-05 02:16 UTC, alan-barzilay commented on src/help.sh
> +}
done

2021-04-05 02:22 UTC, alan-barzilay commented on kw
> +        kworkflow_help
done, see #226

2021-04-05 23:42 UTC, rodrigosiqueira commented on src/help.sh
> +    "\tboot,bo - TODO\n" \
Maybe we can open an issue to delete this option.

2021-04-05 23:55 UTC, rodrigosiqueira commented
Hi @alan-barzilay 
Your patch is almost perfect. I have few comments:
1. Take care with extra spaces at the end of lines; use `git log -p`, and you will see it. Also, do not add extra unnecessary lines in the code (see config_manager_help).
2. Your commit message does not describe well your work. 
3.

2021-04-07 17:51 UTC, alan-barzilay commented on src/help.sh
> +    "\tboot,bo - TODO\n" \
done, #229

2021-04-07 23:03 UTC, alan-barzilay commented
@rodrigosiqueira I have updated the series, please let me know if there is anything else to change

2021-04-10 20:42 UTC, rodrigosiqueira commented
Hi @alan-barzilay 
I did a few changes in your commits and applied them to the unstable branch. See:

https://github.com/kworkflow/kworkflow/commit/cd9463d4e30c6f400821b5d3f9586cf667da120a

2021-04-10 20:42 UTC, closed without merging