Kw pomodoro label and description
kworkflow/kworkflow pull request #292
Opened 2021-05-31 00:39 UTC by rodrigosiqueira

This is part of the work to add Pomodoro with a report to users. This PR intends to:

1. Add labels to a specific timebox;
2. Add description associated to a label;
3. Store data.

@magalilemes since you're working on things related to data, this PR might be something that you want to take a deep look at.

2021-06-02 18:36 UTC, magalilemes requested changes
Everything seems to be alright. That's an awesome patch! 🙃

2021-06-02 18:36 UTC, magalilemes commented on tests/kw_string_test.sh
> +  assert_equals_helper 'Empty string should be 0 lenght' "$LINENO" '0' "$output"
lenght should be length

2021-06-02 18:36 UTC, magalilemes commented on src/pomodoro.sh
>      options_values['SHOW_TIMER']=0
`pomodoro_help()` has to be updated to show the new options

2021-06-03 16:35 UTC, kwy95 commented on documentation/man/kw.rst
> +One helpful feature associated with timers is the *--label|-l** option since it
Shouldn't `*--label|-l**` be `**--label|-l**`? Or `*--label|-l*`?

2021-06-03 21:04 UTC, kwy95 requested changes

2021-06-03 21:04 UTC, kwy95 commented on documentation/man/kw.rst
> +p, pomodoro --set-timer|-t INTEGER[h|m|s] [--label|-l STRING [--description|-d STRING] ] | --current
Here it isn't explicit that you can use `--current` or `-c`

2021-06-08 11:19 UTC, rodrigosiqueira commented
Hi,
I updated this entire series.
@magalilemes @joaoseckler @alan-barzilay @kwy95 could you review it?

2021-06-08 11:46 UTC, kwy95 commented on src/kw_string.sh
> +  value=$(echo "$value" | xargs)
Could this use the function `str_trim` ?

2021-06-11 17:52 UTC, alan-barzilay commented
the kw file is not using include for the pomodoro flag, since this PR is fixing the use of include inside the pomodoro file, maybe we should add this change to the kw file as well @rodrigosiqueira

2021-06-15 00:01 UTC, merged