Remove unnecessary variables from kw file
kworkflow/kworkflow pull request #293
Opened 2021-06-01 01:20 UTC by magalilemes

This PR removes the config_files_path and statistics_path variables set in the kw file, as well as makes the necessary adjustments for it.

Closes #287

2021-06-01 23:39 UTC, joaoseckler requested changes
The title of the commit is duplicated in it's body. Other than that, looks good to me! 

For the future, I was wondering if these folders in the user's home folder shouldn't be configurable...

2021-06-02 00:08 UTC, magalilemes commented
@joaoseckler my bad. I updated the commit message. thx for noticing.

2021-06-02 00:16 UTC, joaoseckler approved these changes

2021-06-02 22:36 UTC, rodrigosiqueira commented
Hi @magalilemes ,
Great patch!

Merged https://github.com/kworkflow/kworkflow/commit/e79f3c1fb5c612fd19f9dbe460eca94e534e5e36

Thanks

2021-06-02 22:36 UTC, closed without merging