Change output for test files not found
kworkflow/kworkflow pull request #313
Opened 2021-06-09 23:48 UTC by magalilemes

This PR modifies the output when trying to individually run tests files that don't exist. The current output is

```
$ ./run_tests.sh test wrong_test_name
Test file  not found.
=========================================================
Total: 1 test file(s)
1 test file(s) NOT FOUND

Take a look at:
```

and I've changed it to be
```
Test file 'wrong_test_name' not found.
=========================================================
Total: 1 test file(s)
1 test file(s) NOT FOUND
```
Closes #284

2021-06-10 15:01 UTC, alan-barzilay requested changes

2021-06-11 01:07 UTC, alan-barzilay approved these changes

2021-06-11 11:47 UTC, rodrigosiqueira requested changes
Hi @magalilemes,
I just have two comments.

2021-06-11 11:47 UTC, rodrigosiqueira commented on run_tests.sh
> +    if [[ -n $test_failure_list ]]; then
Double-quote

2021-06-11 11:47 UTC, rodrigosiqueira commented on run_tests.sh
> +      if [[ -n $target ]]; then
Double-quote

2021-06-11 23:54 UTC, rodrigosiqueira commented
Thanks a lot for this fix. Merged, see: https://github.com/kworkflow/kworkflow/commit/8c928c574f8d60347a29781c2a00955ac725472b

2021-06-11 23:54 UTC, closed without merging