Show hardware information.
kworkflow/kworkflow pull request #314
Opened 2021-06-10 00:31 UTC by magalilemes

This PR is far from ready, and it is a first attempt into showing hardware information from remote machines. To use it, run `kw statistics --remote IP PORT`, and then if everything is okay, it will show an output like the one below, providing information about the CPU, RAM, and type of storage devices.

```
CPU:
        Name: QEMU Virtual CPU version 2.5+
        Frequency:
                CPU MHz:             2304.066
RAM:
        Total RAM: 2037488 kB
Storage devices:
        fd0    rotational
        sda    rotational
        sr0    rotational
```

I haven't added tests yet, and the option still doesn't provide warnings when users mistakenly use the command. I also need to add another option for showing hardware information from the local machine. But before I proceed, I would like to receive feedback on what's been done so far.

2021-06-10 15:11 UTC, alan-barzilay commented
have you tried inxi? it could be a quicker but dirtier way of accomplishing this.

2021-06-10 15:24 UTC, magalilemes commented
@alan-barzilay I haven't. I didn't even know about this. I'll take a look. Thanks

2021-06-11 23:19 UTC, rodrigosiqueira requested changes
Hi Magali,

This is a very nice step toward the hardware information. I would like to suggest a different direction here:

Soon we will need a mechanism to capture hardware information from local, remote, and virtual machines. For this reason, we need something more robust here; I think you could create a new file named device_info_manager (please, see if you find a better name). This file will have functions for collecting this sort of data:
1. RAM
2. CPU
3. DISK
4. OS Device

This file will need some support function for getting those data from a local machine, remote, and virtual machine. Additionally, you will probably need something for dealing with a data store and formatting in that file. See the below draft:

```
# file: src/device_info_manager.sh
include 'remote.sh'

function get_ram()
{
  local target="$1"
  ...
  case "$target" in
    1) # VM_TARGET
    2) # LOCAL_TARGET
    3) # REMOTE
     ssh_to_remote_get_ram()
     ssh_to_remote_get_cpu()
     ...
     ;;
  esac
}

function get_cpu()
{
  # Same idea as above
}

function get_disk()
{
  # Same idea as above
}


function collect_hardware_data()
{

...
  mem=$(get_mem "param1" ...)
  cpu=$(get_mem "param1" ...)
...
  process_all_data()
  display_data()
}


```

Keep in mind that from the data statistics perspective, we probably want to separate data from the remote and local machines. Anyway, I see a series that looks like this:

1. Patch1: Basic data collect for local machine;
2. Patch2: Basic data collect for virtual machine;
3. Patch3: Basic data collect for remote machine;
4. Patch4: Find a way to associate host machines to statistics.

Finally, most of this information is natively available in all distro. For this reason, I don't recommend adding an external dependency (we don't need anything fancy).

2021-06-13 13:54 UTC, magalilemes commented on src/statistics.sh
> +  if [[ ! $info_request == 'remote' ]]; then
Ok! I'll change `info_request` to `target` when refactoring statistics in #276. wdyt?

2021-06-13 19:23 UTC, rodrigosiqueira commented on src/statistics.sh
> +  if [[ ! $info_request == 'remote' ]]; then
Btw, I think you need to focus on my comments in the conversation section. I think you'll need to rethink your approach here.

2021-06-13 21:21 UTC, magalilemes commented on src/statistics.sh
> +  if [[ ! $info_request == 'remote' ]]; then
Yes, I'm focusing on it, and I like all this new direction you pointed out in the conversation better.

2021-06-14 22:41 UTC, rodrigosiqueira commented on src/statistics.sh
> +  if [[ ! $info_request == 'remote' ]]; then
Nice. I think the new set of changes will be much different from this one; for this reason, I would like to suggest you close this PR and open a new one when you have another version.

2021-06-15 01:29 UTC, closed without merging