Improve bash_autocomplete file
kworkflow/kworkflow pull request #352
Opened 2021-06-30 01:37 UTC by magalilemes

This PR fixes two minor things in src/bash_autocomplete.sh: it removes options from `kw_options` that are not supported by kw, and adds the ones that are supported and were missing. It also fixes [SC2207](https://github.com/koalaman/shellcheck/wiki/SC2207).

2021-06-30 15:14 UTC, alan-barzilay approved these changes

2021-06-30 22:43 UTC, joaoseckler requested changes

2021-06-30 22:43 UTC, joaoseckler commented on src/bash_autocomplete.sh
> +                mount mo umount um vars v up u codestyle c configm g
`kw v` was dropped since the introduction of `kw -v`! See commit `f8af2abeae4265cc0d55fd9f3544427b02ffadd1` and pull request #169.

2021-06-30 22:45 UTC, joaoseckler commented
For another PR, I think it would be nice if kw had a more complete autocompletion feature. For example, it would be nice if

`kw d --rem<TAB>`

would complete to

`kw d --remote`

2021-07-01 13:05 UTC, rodrigosiqueira commented
Hi @magalilemes , thanks for your patch. Merged to unstable branch.

@alan-barzilay I noticed that our code coverage is looking at the autocomplete file, could you make a patch to make codecov ignore this?

2021-07-01 13:05 UTC, closed without merging