Introduce backup option
kworkflow/kworkflow pull request #384
Opened 2021-07-14 16:55 UTC by magalilemes

This PR introduces `kw backup`. There are two options for this feature:
- By invoking `kw backup [path]`, a tar file named _backup.tar_ is created in the directory `[path]`
- If you run `kw backup --restore [tar file path]`, the tar file found in ` [tar file path]` will be extracted into `~/.kw`.

2021-07-19 23:43 UTC, rodrigosiqueira requested changes
First of all, thanks a lot for your PR. I already added some comments, but I have some concerns about the restore process; I think we cannot blindly replace what the user has... We need something that checks things, notifies users, and updates without messing with the user data. One idea that I had was:

1. Decompress the tar file in the `.cache` directory.
2. Start your backup for the config file part. Before replacing anything, check if the files are equal; I think md5 can be very useful for comparing files. If the files are the same, don't do anything. If they are different, let the user know and ask them if they really want to replace them (ask them per file here since config file is super important). You might want to show a diff.
3. For the statistic and pomodoro part, you can use the same md5 approach. However, if you see something different, you can ask the user (I think one time is enough for everything) and add the diff between the two files if the user wants to aggregate.

You probably want to add a flag `--force` that just replaces everything as you have now.

Ps.: We discuss more this later.

2021-07-19 23:43 UTC, rodrigosiqueira commented on documentation/man/kw.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`~~~` should fit the title size perfectly.

2021-07-19 23:43 UTC, rodrigosiqueira commented on documentation/man/kw.rst
> +stored in PATH, containing all the data found in the KW_DATA_DIR folder.
For backup, let's assume `$PWD` if user does not provide `<path>`

2021-07-19 23:43 UTC, rodrigosiqueira commented on src/backup.sh
> +    create_backup "${options_values['BACKUP_PATH']}"
Add return here.

2021-07-19 23:43 UTC, rodrigosiqueira commented on src/backup.sh
> +  local flag="$2"
Let's set `SILENT` as the default flag.

2021-07-19 23:43 UTC, rodrigosiqueira commented on src/backup.sh
> +  compress_cmd="tar -C $KW_DATA_DIR -czf $path/backup.tar.gz ."
Use `kw-backup.tar.gz` as a name.

2021-07-19 23:43 UTC, rodrigosiqueira commented on src/backup.sh
> +  fi
If the backup operation ends without any problem, let's tell the user by printing a successful message and tell them where the back can be found.

2021-07-19 23:43 UTC, rodrigosiqueira commented on src/backup.sh
> +  local path="$1"
Let's assume `$PWD` as the default path.

2021-08-01 23:43 UTC, rodrigosiqueira commented
@magalilemes let me know when you have a new version.

2021-08-03 02:28 UTC, magalilemes commented
@rodrigosiqueira I have a new version, but it's not done yet. I tried to follow your idea about replacing the files when extracting. I applied the idea to both the config and pomodoro folder. If I approached the problem correctly, then I'll just implement it to statistics as well.

For now, an example of output from running `kw backup --restore kw-backup.tar.gz` would be:

```
We found a file named lala in your kw data directory.
--- /home/magali/.kw/configs/configs/lala       2021-08-02 22:54:05.872972169 -0300
+++ /home/magali/.cache/tmp-kw-backup/configs/configs/lala      2021-04-09 21:07:05.000000000 -0300
@@ -1,6 +1,6 @@
 #
 # Automatically generated file; DO NOT EDIT.
-# Linux/x86_64 5.12.0-rc4 Kernel Configurat
+# Linux/x86_64 5.12.0-rc4 Kernel Configuration
 #
 CONFIG_CC_VERSION_TEXT="gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0"
 CONFIG_CC_IS_GCC=y
Do you want to replace it and its metadata? [y/N] 
We found a file from 2021/06/02 in your kw pomodoro directory.
Do you want to:
(1) Replace all duplicate files with backup
(2) Keep all the old files
(3) Aggregate all old and backup files
3
patching file /home/magali/.kw/pomodoro/2021/06/02
```
In general, we're checking for duplicates and then copying each file individually.

For config files, kw will check if the files have the same name, and if they do, then it will compare the files. If they're different, then it will prompt a message saying that those files are different, alongside a diff showing that. Then it will ask the user if they want the file in `KW_DATA_DIR` to be replaced or not.

For pomodoro (and possibly statistics), each file will be checked the same way as configs and if one file is detected to be a duplicate, kw will give the user 3 options - as seen in the example above - that will be used for all the other files.

I haven't written the tests for this new version, and the help section wasn't updated either.

2021-08-07 19:08 UTC, rodrigosiqueira requested changes
Hi @magalilemes ,
You are on the right path here, I added a lot of comments, try to address every one of them. Also, for your next version, try the following manual tests:

0. Make sure that you have some data in the `~/.kw` dir.
1. Generate a backup file.
2. Rename your current `.kw`, e.g, `mv ~/.kw ~/.xpto_kw`
3. Try to restore the backup; you should have something equal to `~/.xpto_kw`

Don't forget to add tests as well.

Thanks.

2021-08-07 19:08 UTC, rodrigosiqueira commented on src/backup.sh
> +      diff -u "$KW_DATA_DIR/configs/configs/$config_file" "$file"
Add `--color=always`. It will make the output better to read :)

2021-08-07 23:26 UTC, magalilemes commented on src/backup.sh
> +function backup_parser()
parse_backup_options, right? 😆

2021-08-07 23:30 UTC, magalilemes commented on src/backup.sh
> +  echo -e "kw backup:\n" \
In src/help.sh? I did, or is it something else?

2021-08-07 23:49 UTC, rodrigosiqueira commented on src/backup.sh
> +  echo -e "kw backup:\n" \
Yes, src/help.

2021-08-07 23:49 UTC, rodrigosiqueira commented on src/backup.sh
> +function backup_parser()
Yes :P

2021-08-10 00:48 UTC, rodrigosiqueira requested changes
Hi @magalilemes ,

I added a couple of comments.

Thanks.

2021-08-10 19:23 UTC, magalilemes commented on src/backup.sh
> +function restore_pomodoro_and_statistics()
Sure, there would be some duplicate code, but I get your point.

2021-08-11 12:25 UTC, rodrigosiqueira commented
Hi @magalilemes , please, do not forget to update your PR.

2021-08-11 17:09 UTC, magalilemes commented on src/backup.sh
> +  compress_cmd="tar -C $KW_DATA_DIR -czf $path/$file_name ."
Compress everything inside the current folder tar just changed into, namely $KW_DATA_DIR

2021-08-11 17:12 UTC, magalilemes commented on tests/backup_test.sh
> +  output=$(restore_backup tests/samples/kw-backup-2021-08-07_23-42-51.tar.gz)
It is but I added a compressed file to the tests samples for testing purposes

2021-08-15 14:14 UTC, rodrigosiqueira requested changes
Hi @magalilemes ,
Nice series! I added a couple of comments.
Thanks.

2021-08-15 14:14 UTC, rodrigosiqueira commented on src/kwlib.sh
> +# @ file_path: path to a file
Document the behavior if an empty string is passed to one of the parameters.

2021-08-15 14:14 UTC, rodrigosiqueira commented on documentation/man/features/backup.rst
> +=========
@kwy95 Could you review the documentation part?

2021-08-15 14:14 UTC, rodrigosiqueira commented on documentation/man/features/backup.rst
> +  from KW_DATA_DIR with the backup, you may use the \--force option.
Highlight `--force` with an underscore.

2021-08-15 14:14 UTC, rodrigosiqueira commented on src/backup.sh
> +function restore_pomodoro()
You create this function, but you did not use it.

2021-08-15 14:14 UTC, rodrigosiqueira commented on src/backup.sh
> +    restore_pomodoro_and_statistics
I suppose we want to drop this in favor of restore_pomodoro and restore_statistics.

2021-08-15 14:14 UTC, rodrigosiqueira commented on src/backup.sh
> +      done
I think you can try to create a function that encapsulates this idea since it is shared between restore statistics and Pomodoro.

2021-08-15 14:14 UTC, rodrigosiqueira commented on src/backup.sh
> +    '  backup (-r | --restore) <path> [(-f | --force)] - Extract a tar.gz file into kw data directory'
@kwy95 What is your feedback on this part?

2021-08-15 14:14 UTC, rodrigosiqueira commented on tests/backup_test.sh
> +  output=$(echo 'y' | restore_config)
Maybe I missed something, but did you added `n`?

2021-08-16 15:49 UTC, magalilemes commented on tests/backup_test.sh
> +  output=$(echo 'y' | restore_config)
Yes, [here](https://github.com/kworkflow/kworkflow/pull/384/files#diff-432214475775693514da4e82867c3b45b6cb029df81d97dc5cc2ebacbe9748f3R81)

2021-08-16 18:36 UTC, kwy95 requested changes
Added a few pointers about the documentation.

2021-08-16 18:36 UTC, kwy95 commented on documentation/man/features/backup.rst
> +To restore a backup, use the \--restore option. Suppose you want to restore the
Enclose flags and code in double backticks, documents and files in double asterisks, and variables and palceholders in single asterisks.

2021-08-16 19:08 UTC, magalilemes commented on src/backup.sh
> +    '  backup (<path>) - Create a compressed file containing kw data' \
It's optional, so should it be [<path>] instead?

2021-08-16 19:46 UTC, kwy95 commented on src/backup.sh
> +    '  backup (<path>) - Create a compressed file containing kw data' \
Yes, if it's optional it should be square brackets, parentheses are used for grouping.

2021-08-17 12:07 UTC, rodrigosiqueira requested changes
Hi @magalilemes ,
Thanks a lot for this new version; I just added a few extra comments. I think we are close to finishing this.
Thanks

2021-08-17 12:07 UTC, rodrigosiqueira commented on src/backup.sh
> +  fi
let's use kw_parse and kw_parse_get_errors

2021-08-17 12:07 UTC, rodrigosiqueira commented on src/backup.sh
> +  fi
Did you add a test that reaches this condition?

2021-08-17 12:07 UTC, rodrigosiqueira commented on tests/backup_test.sh
> +  done)
uouuuu... mapfile :)
Add a brief comment that explains what these set of line goals are.

2021-08-17 12:07 UTC, rodrigosiqueira commented on tests/backup_test.sh
> +  done <<< "${tar_files[@]}"
can we replace this with `compare_command_sequence`?

2021-08-17 13:01 UTC, magalilemes commented on src/backup.sh
> +  compress_cmd="tar -C $KW_DATA_DIR -czf $path/$file_name ."
yep

2021-08-18 11:28 UTC, rodrigosiqueira commented
Hi @magalilemes , let me know when you have a new version.

2021-08-21 12:07 UTC, rodrigosiqueira commented
Hi @magalilemes , I merged https://github.com/kworkflow/kworkflow/pull/413 . Could you update this commit to use that?

2021-08-24 10:45 UTC, rodrigosiqueira commented on src/backup.sh
> +  generate_tarball "$KW_DATA_DIR" "$path/$file_name" 'gzip' "$flag"
@magalilemes 
Could you update this line to use the new version of `generate_tarbal`?

2021-08-24 22:55 UTC, magalilemes commented
@rodrigosiqueira I updated the PR to use the new version of `generate_tarball`.

2021-08-24 23:32 UTC, rodrigosiqueira commented
Hi @magalilemes ,
I finally merged this PR (I made some minor changes).

Thanks.

2021-08-24 23:32 UTC, closed without merging