New debug option
kworkflow/kworkflow pull request #397
Opened 2021-08-01 22:25 UTC by rodrigosiqueira

2021-08-02 01:53 UTC, magalilemes reviewed
An entry briefly describing the command in `kworkflow_help()` in `src/help.sh` is missing.

2021-08-02 01:53 UTC, magalilemes commented on src/debug.sh
> +    fi
This implies that if I set `default_deploy_target` to be `vm`, and then run `kw debug --remote` ... or even `kw debug -h`, I'll get a complaint saying that kw debug doesn't support VM.

2021-08-03 14:52 UTC, joaoseckler requested changes

2021-08-03 14:52 UTC, joaoseckler commented on src/remote.sh
> +  iterative_output=${iterative_output:-''}
I think this line adds nothing, right? If "$7" is not supplied, then `iterative_output` has the same value as the default, which is `''` (null string).

2021-08-03 14:52 UTC, joaoseckler commented on src/remote.sh
> +  local iterative_output="$7"
I think we should document these options above the function

2021-08-30 12:29 UTC, rodrigosiqueira commented
@kwy95 could you review the documentation?

2021-08-31 12:39 UTC, kwy95 requested changes
Biggest thing is to separate the documentation on a dedicated file and add it to the man pages,  and then update the help function.
I also think we should discuss a standardization of the error messages, specially on how to display the LINENO variable, as now it is displayed in a myriad of different ways.
And in trying to fulfill #382 consider using printf instead of echo.

2021-08-31 12:39 UTC, kwy95 commented on tests/utils.sh
> +    echo "-----"
I've slowly started to change change all `echo`s to `printf`s, consider changing them here.
Also, use single quotes where appropriate.

2021-08-31 12:39 UTC, kwy95 commented on src/debug.sh
> +    msg="Something went wrong in the listing process. Please, check if"
Single quotes

2021-08-31 12:39 UTC, kwy95 commented on src/debug.sh
> +# EVENT[:SPECIFIC_EVENT[[filter]][,SPECIFIC_EVENT[[filter]],...]][;EVENT...]
Use the placeholder syntax mentioned before

2021-08-31 12:39 UTC, kwy95 commented on src/debug.sh
> +  short_options='f,h,e,c,h,d,l,k'
`h` appears twice

2021-08-31 12:39 UTC, kwy95 commented on src/debug.sh
> +}
Use the new help format with the generated man page and printf

2021-09-06 13:07 UTC, rodrigosiqueira commented
Hi @kwy95 ,
I address most of your comments. In particular, this update has many improvements in the documentation; please, let me know if the new version looks good for you.

2021-09-09 16:50 UTC, kwy95 requested changes
Apart from my comments you need to rebase your changes and change the `echo`s with `printf`s. Also review the quote usage, I marked a few of them, but might have missed some as well

2021-09-09 16:50 UTC, kwy95 commented on tests/utils.sh
> +  equal=$(echo "${expected[@]}" "${result_to_compare[@]}" | tr ' ' '\n' | sort | uniq -u)
```suggestion
  equal=$(printf '%s\n' "${expected[*]} ${result_to_compare[*]}" | tr ' ' '\n' | sort | uniq -u)
```

2021-09-09 16:50 UTC, kwy95 commented on tests/utils.sh
> +    printf '%s\n' '-----'
```suggestion
    printf '%s\n' 'Diff:' \
      '-----' \
      "$equal" \
      '-----'
```

2021-09-09 16:50 UTC, kwy95 commented on src/debug.sh
> +  # if [[ -n "$event" || (-n "$list" && -z "$event") ]]; then
Why is this here?

2021-09-09 16:50 UTC, kwy95 commented on src/debug.sh
> +    '  debug (--event | -e) \"<syntax>\" - Trace specific event' \
```suggestion
    '  debug (--cmd | -c) "command" - Trace log while running a command in the target.' \
    '  debug (--event | -e) "<syntax>" - Trace specific event' \
```

2021-09-09 16:50 UTC, kwy95 commented on src/debug.sh
> +    '  debug (--history | -h) - Store trace logs in a file' \
Again, isn't this `-k`?

2021-09-09 16:50 UTC, kwy95 commented on src/debug.sh
> +      test_mode)
This option is not on the list of options passed to `getopt` so its not going to be parsed correctly. Is this even needed? I noticed that `debug_manager()` is not invoked on the test suite.

2021-09-09 16:50 UTC, kwy95 commented on src/debug.sh
> +    -- "$@")"
Maybe use `kw_parse` instead?

2021-09-09 16:50 UTC, kwy95 commented on src/debug.sh
> +  #if [[ "$option" == "$LIST_OPTION" && -z "$event" ]]; then
Remove before final version

2021-09-09 16:50 UTC, kwy95 commented on src/debug.sh
> +# manipulation, including enabling, disable, and list events.
```suggestion
# manipulation, including enabling, disabling, and listing events.
```

2021-09-09 16:50 UTC, kwy95 commented on src/debug.sh
> +  local filter=""
Single quotes

2021-09-09 16:50 UTC, kwy95 commented on src/debug.sh
> +  enable=${enable:-"1"}
Single quotes

2021-10-01 11:14 UTC, rodrigosiqueira commented
This PR has been opened for a long time; I decided to merge it since this is working and updated.

2021-10-01 11:14 UTC, closed without merging