src: kw sendemail support WIP
kworkflow/kworkflow pull request #425
Opened 2021-08-19 22:40 UTC by kwy95

WIP implementation of `kw send-email`

2021-08-23 19:12 UTC, magalilemes commented
I noticed you're using 'kw s' as the short option for 'kw send-email', but we're already using 'kw s' for 'kw ssh'.

2021-08-23 20:00 UTC, kwy95 commented
> I noticed you're using 'kw s' as the short option for 'kw send-email', but we're already using 'kw s' for 'kw ssh'.

@magalilemes It's actually `kw se` for now, but I'm open to suggestions for better names. I have also considered `kw mail`, probably without a short version as most of the obvious options are already being used.

2021-08-24 10:43 UTC, rodrigosiqueira requested changes
Hi @kwy95 ,

I did not review this PR in detail because I noticed that this is just something to start a discussion. I suggest that you close this PR and create a new one that has this:

1. Commit 1: Add basic support for git send-email
 * Add: kw mail --setup --smtpserver "" --smtpuser ""
 * Add tests and documentation

2. Commit 2: Add support to verify
 * Add: kw mail --setup --verify
 * Add test and doc

3. Commit 3: Add support to interactive setup
 * Add: kw mail --setup -i
 * Add tests and doc

That's it for your first version. After this new PR gets merged, you should focus on --send.

2021-08-24 10:43 UTC, rodrigosiqueira commented on src/kw_config_loader.sh
> +    has_local_config_path='Yes'
If you want, send this tiny fix in another PR. It does not make sense to add this in this PR.

2021-08-29 14:25 UTC, rodrigosiqueira commented
@kwy95 ,
I'm going to close this PR since you have a new one at:
https://github.com/kworkflow/kworkflow/pull/437/commits/e1946d8a3eaab70b6a36aadb950d1941f62b19be

2021-08-29 14:25 UTC, closed without merging