Check if kernel image is readable before mounting vm
kworkflow/kworkflow pull request #427
Opened 2021-08-24 01:10 UTC by magalilemes

If the kernel image isn't readable, guestmount throws a few errors, and the virtual machine cannot be mounted. Here we check if the kernel image is readable, and if it isn't we ask the user to give it read permission.

2021-08-24 12:05 UTC, rodrigosiqueira requested changes

2021-08-24 22:57 UTC, magalilemes commented on src/vm.sh
> +    cmd_manager "$flag" "sudo chmod +r /boot/vmlinuz-$(uname -r)"
> ```
> curl $(python3 -c "import apt, os; print(apt.cache.Cache()['linux-image-' + os.uname().release].versions[0].uri)") | dpkg-deb -x - .
> ```
@rodrigosiqueira I think this one command is not meant for making the kernel image readable. Can you enlighten me on what it does? It gets a kernel image and then extracts it with dpkg-deb?


> Also, it looks like that the correct command should be something like this:
> 
> ```
> sudo dpkg-statoverride --update --add root root 0644 /boot/vmlinux-$(uname -r)
> ```
This one works too!!

2021-08-31 00:39 UTC, magalilemes commented
I couldn't really find an alternative that didn't require `sudo`. Should  `sudo dpkg-statoverride --update --add root root 0644 /boot/vmlinux-$(uname -r)` be used or the command from the current code is fine?
I'll add tests as soon as this is solved.

2021-08-31 23:00 UTC, rodrigosiqueira commented
> I couldn't really find an alternative that didn't require `sudo`. Should `sudo dpkg-statoverride --update --add root root 0644 /boot/vmlinux-$(uname -r)` be used or the command from the current code is fine?
> I'll add tests as soon as this is solved.

Ok, if there is no other way, do you know the advantage of using the above command compared with chown?

2021-09-03 15:52 UTC, rodrigosiqueira requested changes
I just have one final observation. Could you address that? Do not forget to update the test with my latest suggestion.

2021-09-03 15:52 UTC, rodrigosiqueira commented on src/vm.sh
> +    cmd_manager "$flag" "sudo dpkg-statoverride --update --add root root 0644 ${prefix}boot/vmlinuz-$(uname -r)"
This command will only work on Debian-based systems; check if the host system is Debian-based before you use this command. If it is not a Debian system, use the standard chmod.

2021-09-06 13:29 UTC, rodrigosiqueira commented
Hi @magalilemes ,
Thanks a lot for fixing this issue. Merged to the unstable branch.

2021-09-06 13:29 UTC, closed without merging