Deploy simplify prepare functions
kworkflow/kworkflow pull request #444
Opened 2021-09-03 17:55 UTC by rodrigosiqueira

This PR is a follow-up from https://github.com/kworkflow/kworkflow/pull/441. Here, I'm trying to simplify the preparation functions in the deploy.

2021-09-04 19:44 UTC, kwy95 requested changes
Small nitpicks, otherwise looks good.

2021-09-04 19:44 UTC, kwy95 commented on tests/deploy_test.sh
> +  assert_equals_helper "Infer kernel image" "$LINENO" "$expected_cmd" "$output"
```suggestion
  assert_equals_helper 'Infer kernel image' "$LINENO" "$expected_cmd" "$output"
```

2021-09-05 21:33 UTC, rodrigosiqueira commented
Thanks @kwy95 
PR updated.

2021-09-06 15:47 UTC, kwy95 approved these changes

2021-09-06 18:28 UTC, rodrigosiqueira commented
Thanks @kwy95

2021-09-06 18:28 UTC, closed without merging