doc: Introduce configm tutorial
kworkflow/kworkflow pull request #446
Opened 2021-09-06 15:39 UTC by rodrigosiqueira

This is part of #244

Signed-off-by: Rodrigo Siqueira <rodrigosiqueiramelo@gmail.com>

2021-09-08 21:15 UTC, kwy95 requested changes
I left a few fixes. Also, remember to change the index.rst file as I mentioned in #445

2021-09-08 21:15 UTC, kwy95 commented on documentation/tutorials/configm.rst
> +it.
```suggestion
The above command displays the configs labels and descriptions associated to
it.
```

2021-09-08 21:15 UTC, kwy95 commented on documentation/tutorials/configm.rst
> +kernel tree; if you have, it will ask you if you want to override it or not.
```suggestion
kernel tree; if you do, it will ask you whether to override it or not.
```

2021-09-08 21:15 UTC, kwy95 commented on documentation/tutorials/configm.rst
> +repository managed by kw; if you really want to see it, you check the folder::
```suggestion
The configm option makes it easier for you to keep track of different config
files. Another advantage of using this feature comes from the fact that the
backup option also saves these files, enabling you to easily move your config
files. Finally, under the hood, these config files are maintained under a git
repository managed by kw; if you really want to see it, you can check the
folder::
```

2021-09-11 14:17 UTC, rodrigosiqueira commented on documentation/tutorials/configm.rst
> +
What do you mean by reference?

2021-09-11 14:23 UTC, rodrigosiqueira commented
Hi @kwy95 ,
I applied all your suggestions in this new version; thanks a lot for your review.

2021-09-11 22:14 UTC, kwy95 commented on documentation/tutorials/configm.rst
> +
A line like this:
```
.. _configm-tutorial:
```

2021-09-11 22:44 UTC, kwy95 requested changes
Just some final adjustments.

2021-09-11 22:44 UTC, kwy95 commented on documentation/tutorials/configm.rst
> +description option to describe your config file better. For example, you could
```suggestion
description option to better describe your config file. For example, you could
```

2021-09-11 22:44 UTC, kwy95 commented on documentation/tutorials/configm.rst
> +To show all your config files saved user kw, you just need to use::
```suggestion
To show all the config files saved using kw, you just need to use::
```

2021-09-11 22:44 UTC, kwy95 commented on documentation/tutorials/configm.rst
> +  kw configm --list # kw configm -l
```suggestion
  kw configm --list # kw g -l
```

2021-09-11 22:44 UTC, kwy95 commented on documentation/tutorials/configm.rst
> +to it.
```suggestion
to them.
```

2021-09-13 22:21 UTC, rodrigosiqueira commented
Hi @kwy95 ,
Thanks for your review. I already update this PR.

2021-09-14 19:56 UTC, kwy95 requested changes
Just the one change and this should be done!

2021-09-14 19:56 UTC, kwy95 commented on documentation/tutorials/configm.rst
> +your config file well, and for this reason, the `configm` also provides a
```suggestion
your config file well, and for this reason, `configm` also provides a
```

2021-09-14 22:56 UTC, rodrigosiqueira commented
@kwy95 updated.

2021-09-14 23:45 UTC, kwy95 approved these changes

2021-09-16 22:16 UTC, rodrigosiqueira commented
Merged, thanks

2021-09-16 22:16 UTC, closed without merging