Add interaction support to init.sh for ssh setup and remote config
kworkflow/kworkflow pull request #502
Opened 2021-10-28 20:59 UTC by melloguel

In this commit we modified init.sh to look for the --interactive
(or -i) options when parsing arguments. If these options are found,
the script will attempt to interactively detect and setup SSH in
the user's system. Prompts are added to allow the user to interact
with this process and skip steps if desired. We also added an
interactive configuration step for the user's remote connection
settings after SSH is setup. These functionalities are intended to
provide a better user experience for new users who may never have
setup KW before. Functionalities yet to be implemented for this
goal are commented with a #TODO: in the body of the script.

Co-authored-by: Miguel de Mello Carpi <49130937+melloguel@users.noreply.github.com>
Co-authored-by: Lourenço Henrique Moinheiro Martins Sborz Bogo <62181861+louhmmsb@users.noreply.github.com>
Co-authored-by: Eduardo Brancher Urenha <49043437+EduBrancher@users.noreply.github.com>

2021-11-08 15:49 UTC, kwy95 requested changes
Thanks for this PR, please review my comments and address the problems I pointed out.
Also, don't forget to add tests.

2021-11-08 15:49 UTC, kwy95 commented on documentation/man/features/init.rst
> +\--interactive:
This is missing the `-i` option. Also, you need to add this option to the synopsis.

2021-11-08 15:49 UTC, kwy95 commented on documentation/man/features/init.rst
> +\--interactive:
Look at `build.rst` for reference.

2021-11-08 15:49 UTC, kwy95 commented on src/init.sh
> +    '  init --interactive - Perform first time setup in an interactive manner. Recommended for new users.'
I just noticed the synopsis on the documentation is missing some of these options, could you create a separate commit to add these options to the man page?
Also, this documentation for the feature can be in the same commit as the feature implementation.

2021-11-08 15:49 UTC, kwy95 commented on src/init.sh
> +
These should happen after variable declarations.

2021-11-08 15:49 UTC, kwy95 commented on src/init.sh
> +    echo
As per our codestyle, don't use `echo`, prefer `printf` instead.

2021-11-08 15:49 UTC, kwy95 commented on src/init.sh
> +    say 'We will ask you a series of questions regarding how do you want to configure kernel workflow.'
How about this?
```suggestion
    say 'We will ask a series of questions to help you configure kw.'
```

2021-11-08 15:49 UTC, kwy95 commented on src/init.sh
> +    echo
Again, no `echo`s

2021-11-08 15:49 UTC, kwy95 commented on src/init.sh
> +	      if [[ $(ask_yN "Do you wish to proceed without configuring SSH?") =~ '0' ]]; then
I think this is a mistake, right?

2021-11-08 15:49 UTC, kwy95 commented on src/init.sh
> +      exit 125 # ECANCELED
These problems pointed out by `shfmt` should be fixed before each commit, as to not introduce any commits that are not compliant with our github workflows.

2021-11-09 12:41 UTC, rodrigosiqueira commented
Hi @melloguel ,
Any update since our discussion?

2021-11-11 19:02 UTC, melloguel commented
Hello, @rodrigosiqueira,
We'll close this PR and do another one with more proper commits.

2021-11-11 19:02 UTC, closed without merging