src: Move the statistics option as a suboption under the report
kworkflow/kworkflow pull request #506
Opened 2021-11-03 23:50 UTC by caiquecamargo

Add a condition while parsing the arguments for the report feature that calls the statistics function when the flag --statistics is
present, as well stopping the user from calling the statistics feature directly.

This is a temporary solution, since both features require modernization on their parsing system.

2021-11-05 22:47 UTC, kwy95 requested changes
As a temporary solution this looks ok, though I am not sure there is a rush to change this behavior until we update the parsers for statistics and report. You also need to update the autocomplete file, and the documentation and help text.

2021-11-09 12:42 UTC, rodrigosiqueira commented
Hi @caiquecamargo ,
From our previous discussion, we agreed on this direction:

1. Modernize report parser
2. Move the statistics option under the report

Any update here?

2021-11-11 20:36 UTC, caiquecamargo commented
Hi @rodrigosiqueira we've sent an update as a draft so we can discuss better on this and see if we are on the right way with the implementation.

Some tests are break but we working on it.

2021-11-15 22:04 UTC, kwy95 requested changes
You removed the statistics option from the parser in the last commit. Also, try to start updating the documentation accordingly.

2021-11-21 15:24 UTC, rodrigosiqueira requested changes
Hi,

I added a couple of comments in the PR and follows other requests:

1. You just need two commits in this PR:
 * Commit 1: Modernize report parser
 * Commit 2: Move --statistics inside the report
2. After your PR, I expect the `statistics.sh` file to become some sort of library that can be used for other parts of the code.
3. In the report section, you will need to add some optional values (see my comments).
4. Make sure that you update the test for this new parser option.

2021-11-21 15:24 UTC, rodrigosiqueira commented on src/report.sh
> +  local short_options='o'
The parameter `output | o` requires a value; in this case, you need to add `:` to indicate that.

Additionally, we need to handle values around `day, week, month, year`, but those are optional. For this reason, you can use `::`. However, we will need to use `=`  to set a value.

2021-11-21 15:24 UTC, rodrigosiqueira commented on src/report.sh
> +      options_values['ERROR']="--output cannot be used with --statistics."
Why we cannot use `--output` with statistics? ihmo, it makes sense.

2021-11-21 15:24 UTC, rodrigosiqueira commented on src/report.sh
> +    fi
What are all of these checks around the output parameter?

2021-11-21 15:24 UTC, rodrigosiqueira commented on src/report.sh
> +  elif [[ -n $1 ]]; then
Why are you checking `$1`? At this point, I expected that `$@` is empty; if not, something might be wrong.

2021-11-21 15:24 UTC, rodrigosiqueira commented on src/statistics.sh
> +    year_statistics "${options_values['YEAR']}"
Currently, `statistics` is the entry point in the `kw` file for the statistic feature. After your refactor, I expect that this code manipulation will abode in the report file.

2021-11-21 15:24 UTC, rodrigosiqueira commented on documentation/man/features/report.rst
> +\--statistics:
This commit should be squashed with the one that enables the `--statistic` option inside the report.

2021-11-21 15:24 UTC, rodrigosiqueira commented on documentation/man/kw.rst
> +  | :ref:`kw-report<report-doc>`
Squash this commit with the one that enables `--statistic` inside `--report`.

2021-11-22 04:43 UTC, kwy95 requested changes
@rodrigosiqueira already covered most problems, I left only a few extra comments.

2021-11-22 04:43 UTC, kwy95 commented on src/report.sh
> +      options_values['ERROR']="Invalid path for the --output argument."
Single quotes.

2021-11-25 22:35 UTC, rodrigosiqueira requested changes

2021-11-25 22:35 UTC, rodrigosiqueira commented on src/report.sh
> +    return
Use `exit` here.

2021-11-25 22:35 UTC, rodrigosiqueira commented on src/report.sh
> +  if [[ "$is_statistics" == 1 ]]; then
How about use `options_values['STATISTICS']`?

2021-11-25 22:35 UTC, rodrigosiqueira commented on src/report.sh
> +    return
Let's create a function for this code.

2021-11-25 22:35 UTC, rodrigosiqueira commented on src/report.sh
> +  local long_options='day::,week::,month::,year::,output:,statistics'
add a short_options to `statistics`, maybe `-s`.

2021-11-26 00:02 UTC, kwy95 requested changes

2021-11-28 21:35 UTC, rodrigosiqueira commented
Please, update your PR with the latest code from the unstable branch, addressing Rubens's comments and fixing the formatter-shfmt issue.

2021-11-30 22:33 UTC, kwy95 requested changes
This is a nice update. I think it would be interesting as a follow up from this to better integrate the statistics output to the report, so that the statistics info is added to the report, I think this would also solve the conflict of using the `--output` option with statistics.

2021-12-01 23:04 UTC, lucastheo commented on documentation/man/kw.rst
> +You can see data related to your kw usage by using the --statistics flag on the report option, see
We opened issue #523 to solve the issue between output and statistics

2021-12-02 05:22 UTC, kwy95 requested changes
Small fixes.

2021-12-02 05:22 UTC, kwy95 commented on src/report.sh
> +        fi
Check this condition after parsing all arguments, as to not impose an order on the options.

2021-12-02 05:22 UTC, kwy95 commented on src/report.sh
> +        fi
Same with this check. Ideally try to unify them.

2021-12-07 12:39 UTC, rodrigosiqueira requested changes

2021-12-07 12:39 UTC, rodrigosiqueira commented on documentation/man/features/report.rst
> +already configured.
Maybe we can make this comment as a note and rewrite it as well. Maybe something like this:
> First of all, for these examples, we suppose that you have the `disable_statistics_data_track` option in your kworkflow.config enabled for a while.

2021-12-07 12:39 UTC, rodrigosiqueira commented on documentation/man/features/report.rst
> +already configured.
Also, keep in mind that this is only related to the `--statistics` option. In other words, this is not valid for the regular report; please, make this distinction explicit to the `--statistics` option.

2021-12-07 12:39 UTC, rodrigosiqueira commented on src/report.sh
> +    '  report [--year[=<year>]] - Report fo the year' \
Drop the `statistics` option in the main help menu. See `src/help.sh` file.

2021-12-07 12:39 UTC, rodrigosiqueira commented on documentation/man/features/report.rst
> +  displays the current month data.
The option `kw report --help` will looks like this for this section:
```
--day[=<year>/<month>/<day>]:
Display day summary. Users have the option to search a specific date by passing an argument that follows the <year>/<month>/<day> format. Not passing anything and gets info about today.

--week[=<year>/<month>/<day>]:
Shows the week summary. If a user does not pass any parameter kw will show the current week statistics. However, users can pass a random date <year>/<month>/<day> and let kw take care to provide a summary related to the week related to the target date.

--month[=<year>/<month>]:
This option shows a report regarding a specific month. Users can search for data related to a specific month by providing a parameter in the <year>/<month> format. If the user does not pass any parameter, kw displays the current month data.

--year[=<year>]:
Exhibits the current year summary if the user does not specify <year>.

--statistics:
Display current date statistics summary.

--statistics [–day[=<year>/<month>/<day>]]:
Display day statistics summary. Users have the option to search a specific date by passing an argument that follows the <year>/<month>/<day> format. Not passing anything and gets info about today.

--statistics [–week[=<year>/<month>/<day>]]:
Shows the week summary. If a user does not pass any parameter kw will show the current week statistics. However, users can pass a random date <year>/<month>/<day> and let kw take care to provide a summary related to the week related to the target date.

--statistics [–month[=<year>/<month>]]:
Shis option shows a report regarding a specific month. Users can search for data related to a specific month by providing a parameter in the <year>/<month> format. If the user does not pass any parameter, kw displays the current month data.

--statistics [–year[=<year>]]:
Exhibits the current year summary if the user does not specify <year>.
```
I don't think it makes sense to explain the date parameters repeatedly. Please, rewrite it by removing the duplication of information.

2021-12-08 12:10 UTC, rodrigosiqueira commented
@caiquecamargo any update here?

2021-12-08 23:06 UTC, caiquecamargo commented
> @caiquecamargo any update here?

We resolve the requested changes.

2021-12-09 19:37 UTC, kwy95 requested changes
Minor fixes.

2021-12-09 19:37 UTC, kwy95 commented on documentation/man/features/report.rst
> +  Display current date statistics summary.
Change this to be more generic and take into account the date parameters. Something like this:
`Display statistics for the given date.`
You could alternatively just add something like `You can choose the date and range with the date options.`

2021-12-14 12:27 UTC, rodrigosiqueira commented
I changed some details and merged this PR with the unstable branch.
Thanks

2021-12-14 12:27 UTC, closed without merging