src: deploy: fix broken pipe message in test_kernel_install_x86_64
kworkflow/kworkflow pull request #516
Opened 2021-11-14 13:37 UTC by isinyaaa

This attemps at fixing the broken pipe error that occurs in the project's CI.

Attempted fix:
[1] - _https://superuser.com/questions/554855/how-can-i-fix-a-broken-pipe-error_

Fixes: #484.

2021-11-15 22:46 UTC, kwy95 requested changes
Thanks a lot for this patch, the unit tests output is much cleaner now. The only weird output we still get on our CI is from statistics not having permissions when trying to create files during `build_test`.
Please just add a small descriptive commit message to your commits apart from `Fixes #XYZ`.

2021-11-15 22:46 UTC, kwy95 commented on tests/build_test.sh
> +  output=$(kernel_build 'TEST_MODE' | tail -n +1 | head -1) # Remove statistics output
Please add a commit message.

2021-11-15 22:46 UTC, kwy95 commented on src/diff.sh
> +  [[ "$TERM" == '' || "$TERM" == 'dumb' ]] && TPUTTERM=' -T xterm-256color'
Please add a commit message.

2021-11-16 00:58 UTC, rodrigosiqueira requested changes
Hi,
I just have a few comments.

2021-11-16 16:46 UTC, kwy95 approved these changes
LGTM

2021-11-19 12:22 UTC, rodrigosiqueira commented
Thanks a lot!
Merged to the unstable branch.

2021-11-19 12:22 UTC, closed without merging