Debug updates
kworkflow/kworkflow pull request #522
Opened 2021-11-26 11:49 UTC by rodrigosiqueira

2021-11-28 20:25 UTC, rodrigosiqueira commented
@kwy95 could you review this PR? I added a new tutorial; it would be nice to have your review in that specific part.

2021-11-30 21:41 UTC, kwy95 requested changes
Apart from the comments I left some of the commits have no messages in them, only the titles.

2021-11-30 21:41 UTC, kwy95 commented on documentation/tutorials/kernel-debug.rst
> +In a few words, every new execution is saved in that folder.
Do the folders contain any files? If so, which ones? It isn't clear to me why I'd want to use this option.

2021-11-30 21:41 UTC, kwy95 commented on documentation/tutorials/kernel-debug.rst
> +#. Stop to collect log
```suggestion
#. Start logging
#. Run the command
#. Stop logging
```

2021-11-30 21:41 UTC, kwy95 commented on documentation/tutorials/kernel-debug.rst
> +Notice that you can put any specific event after the `events:`. Finally, let's
```suggestion
Notice that you can put any specific event after `events:`. Finally, let's
```

2021-11-30 21:41 UTC, kwy95 commented on documentation/tutorials/kernel-debug.rst
> +the most common one, and you can use it like this::
```suggestion
Those are the ftrace algorithms that you can set; function_graph is probably
the most common one, and you can use it like this::
```

2021-12-07 12:19 UTC, rodrigosiqueira commented
Merged to the unstable branch.

2021-12-07 12:19 UTC, closed without merging