src: report: Compatibility of statistiscs with output option
kworkflow/kworkflow pull request #525
Opened 2021-12-06 23:24 UTC by lucastheo

This is a proposal solution to resolve the issue #523 and add option to select between `--statistiscs` or `--pomodoro` or both. 

Obs: This pull request depends on #506 and the commits tree will be resolved when #506 is accept.

2021-12-07 01:25 UTC, kwy95 requested changes
Very nice PR. Please update the documentation accordingly.
I would also prefer if the statistics report appeared after the pomodoro report.

2021-12-07 01:25 UTC, kwy95 commented on src/report.sh
> +    target_time="${options_values['DAY']}"
Switch these lines so they follow the same pattern as the rest.

2021-12-07 01:25 UTC, kwy95 commented on src/report.sh
> +  if [[ -z "${options_values['STATISTICS']}" ]] && [[ -z "${options_values['POMODORO']}" ]] && [[ -z "${options_values['ALL']}" ]]; then
All these tests can be inside a single `[[ ... ]]` like this:
```suggestion
  if [[ -z "${options_values['STATISTICS']}" && -z "${options_values['POMODORO']}" && -z "${options_values['ALL']}" ]]; then
```

2021-12-09 19:47 UTC, kwy95 requested changes

2021-12-09 19:47 UTC, kwy95 commented on documentation/man/features/report.rst
> +  Display current date pomodoro report.
As I mentioned in #506 add/change this to clarify that the date and range can be set with the date options.

2021-12-14 23:33 UTC, rodrigosiqueira commented
@lucastheo any update here?

2021-12-15 13:27 UTC, caiquecamargo commented
> @lucastheo any update here?

We solve the requests and with the merge of the #506 we adjust the commit tree

2021-12-15 16:06 UTC, kwy95 requested changes
Thanks for the update, I left comments with what I believe to be the final little tweaks needed to complete this PR.

2021-12-15 16:06 UTC, kwy95 commented on src/report.sh
> +
Remove this extra line.

2021-12-15 16:06 UTC, kwy95 commented on src/report.sh
> +    grouping_day_data "${options_values['DAY']}"
I just noticed you can use the `target_time` variable in these `if`s
```suggestion
    target_time="${options_values['DAY']}"
    grouping_day_data "$target_time"
```

2021-12-15 16:06 UTC, kwy95 commented on src/report.sh
> +  if [[ -z "${options_values['STATISTICS']}" && -z "${options_values['POMODORO']}" && -z "${options_values['ALL']}" ]]; then
There is no `options_values['ALL']` you don't need to check it here.
```suggestion
  if [[ -z "${options_values['STATISTICS']}" && -z "${options_values['POMODORO']}" ]]; then
```

2021-12-15 17:14 UTC, kwy95 approved these changes
LGTM

2021-12-16 23:35 UTC, rodrigosiqueira commented
Merged,
Thanks

2021-12-16 23:35 UTC, closed without merging