fix: tests failing if user git config not set
kworkflow/kworkflow pull request #572
Opened 2022-03-12 15:21 UTC by listout

This is WIP fix. The configm_test still needs to be fixed.

2022-03-13 22:01 UTC, rodrigosiqueira requested changes
Hi @listout ,
First of all, thanks a lot for your contribution.

Tbh, I'm not sure which issue you are trying to fix. Could you elaborate a little bit more on the commit message?

2022-03-14 15:20 UTC, listout commented
Sorry @rodrigosiqueira for the late reply. I'm trying to fix issue #538. Basically the tests `configm_test` and `explore_test` fail if the global git config (user.name and user.email) are not set.

2022-03-15 11:42 UTC, kwy95 requested changes
This first fix seems to work. Please update the commit message as per: https://kworkflow.org/content/howtocontribute.html#commit-messages

2022-03-15 11:46 UTC, kwy95 commented
@listout I just took a look at the `configm_test` file, and the `tearDown` function removes and recreates the `$SHUNIT_TMPDIR` directory, you can probably circumvent this by also calling `mk_fake_git` after the recreation of the folder.

2022-03-15 14:18 UTC, listout commented
Thank you @kwy95. I'll do what you suggested.

2022-03-15 16:42 UTC, listout commented
@kwy95 I found a new bug. If you run the explore_test with user config set for signing commits (i.e. gpgsign = true), the test fails.

Steps to reproduce:

- Just set global config for signing commits (` git config --global commit.gpgsign true `)
- Run the explore_test

2022-03-15 17:07 UTC, listout commented
Thank you @kwy95. I've changed the commit message. How to get it incorporated into this pull request?

2022-03-15 17:30 UTC, listout commented
@kwy95 I tried putting `mk_fake_git` after the `mkdir -p "$SHUNIT_TMPDIR"` command in `tearDown` (line 48 of configm_test.sh) function, same result, test fails.

Log of the test:

```
>> ./run_tests.sh test configm_test
Running test [configm_test]
=========================================================
test_execute_config_manager_SAVE_fails
test_save_config_file_check_save_failures
test_save_config_file_check_directories_creation
test_save_config_file_check_saved_config
test_save_config_file_check_description
test_save_config_file_check_git_save_schema
ASSERT:230: We expected 2 commits, but we got 0
test_save_config_file_check_force
ASSERT:249: We expected no changes
test_list_config_check_when_there_is_no_config
test_list_config_normal_output
test_execute_config_manager_get_config_invalid_option
test_get_config
test_get_config_with_force
test_execute_config_manager_remove_that_should_fail
test_remove_config
ASSERT:432: We expected , 1 files but got 2
test_cleanup
test_get_config_from_proc
test_get_config_from_boot
test_get_config_from_defconfig
test_fetch_config
test_configm_parser

Ran 20 tests.

FAILED (failures=3)
=========================================================
Total: 1 test file(s)
1 test file(s) FAILED

Take a look at:
-> ./tests/configm_test.sh
```

2022-03-17 11:35 UTC, rodrigosiqueira commented
Hi @listout ,

I was looking into this `configm_test` and `src/configm`. I noticed that we do not give enough attention to this part of the code, and we are aware of that, as you can see in this issue:

https://github.com/kworkflow/kworkflow/issues/454

Focus on this file and improving it could be an excellent way to get into the project.

Anyway, back to your issue. First of all, `configm_tests` really need some serious review and refactor. I made some changes in how the setUp function works, and I also expanded the `mk_fake_git` to have the gpg configuration. Follows the diff file, but keep in mind that this is just a draft; you probably need to dig into the details.

```diff
diff --git a/tests/configm_test.sh b/tests/configm_test.sh
index 45c54a5..95341c3 100755
diff --git a/tests/configm_test.sh b/tests/configm_test.sh
index 45c54a5..95341c3 100755
--- a/tests/configm_test.sh
+++ b/tests/configm_test.sh
@@ -22,22 +22,31 @@ function setUp()
 {
   local -r current_path="$PWD"
 
+  export KW_CACHE_DIR="$SHUNIT_TMPDIR/cache"
+  mkdir "$SHUNIT_TMPDIR/configs"
+  KW_DATA_DIR="$SHUNIT_TMPDIR"
+  configs_path="$KW_DATA_DIR/configs"
+
   cd "$SHUNIT_TMPDIR" || {
     fail "($LINENO) It was not possible to move to temporary directory"
     return
   }
+
   touch .config
   printf '%s\n' "$CONTENT" > .config
+
+  cd "configs" || {
+    fail "($LINENO) It was not possible to move to configs directory"
+    return
+  }
+
+  mk_fake_git
+
   cd "$current_path" || {
     fail "($LINENO) It was not possible to move back from temp directory"
     return
   }
 
-  export KW_CACHE_DIR="$SHUNIT_TMPDIR/cache"
-  mkdir "$SHUNIT_TMPDIR/configs"
-  KW_DATA_DIR="$SHUNIT_TMPDIR"
-  configs_path="$KW_DATA_DIR/configs"
-
   parse_configuration "$KW_CONFIG_SAMPLE"
   declare -la expected_cmd=()
 }
@@ -214,19 +223,24 @@ function test_save_config_file_check_git_save_schema()
     fail "($LINENO) It was not possible to move to temporary directory"
     return
   }
+
   ret=$(save_config_file $NO_FORCE $NAME_1 "$DESCRIPTION_1")
   ret=$(save_config_file $NO_FORCE $NAME_2 "$DESCRIPTION_2")
+
   cd "configs" || {
     fail "($LINENO) It was not possible to move to configs directory"
     return
   }
+
   ret=$(git rev-list --all --count)
+
   cd "$current_path" || {
     fail "($LINENO) It was not possible to move back from configs directory"
     return
   }
 
-  assertTrue "$LINENO: We expected 2 commits, but we got $ret" '[[ $ret = "2" ]]'
+  # 3 commits from mk_fake_git, 2 commits from this test
+  assertTrue "$LINENO: We expected 5 commits, but we got $ret" '[[ $ret = "5" ]]'
 }
 
 function test_save_config_file_check_force()
diff --git a/tests/utils.sh b/tests/utils.sh
index a40827a..ba1cb6f 100755
--- a/tests/utils.sh
+++ b/tests/utils.sh
@@ -182,6 +182,7 @@ function mk_fake_git()
   git config --local user.name 'Xpto Lala'
   git config --local user.email 'test@email.com'
   git config --local test.config value
+  git config --local commit.gpgsign false
```

2022-03-17 14:49 UTC, listout commented
@rodrigosiqueira thank you.

I'm guess it would be alright if I ask questions on here (if I get stuck at some point)?

2022-03-19 03:45 UTC, rodrigosiqueira commented
Yeah, feel free to ask questions here or in the issue.

2022-03-21 11:48 UTC, rodrigosiqueira commented
Hi @listout ,
Could you rebase your change with the latest code from the unstable branch?

2022-03-23 12:31 UTC, kwy95 requested changes
Be careful when rebasing changes and updating your pull requests, this commit has brought some lines from the `master` branch along with your intended changes.

2022-03-23 12:31 UTC, kwy95 commented on README.md
> +[![Build Status](https://travis-ci.org/kworkflow/kworkflow.svg?branch=master)](https://travis-ci.org/kworkflow/kworkflow)
Careful when rebasing your changes, these should not be here.

2022-03-23 12:31 UTC, kwy95 commented on tests/explore_test.sh
> +  mk_fake_git
This should be the only changed line in this commit.

2022-03-23 17:55 UTC, listout commented
Damn, thanks @kwy95. I'll fix it.

2022-03-24 10:36 UTC, listout commented
Note for other contributors coming to this issue. I'm getting quite busy with life and it's taking longer than usual to fix this bug. If you have a working patch/fix fell free to open a pull request, I'll close this one.

2022-03-27 12:39 UTC, rodrigosiqueira commented
Hi @listout , thanks for your PR and for keeping working in the PR. Could you update it based on @kwy95 comments?

2022-03-27 14:47 UTC, listout commented
Hi @rodrigosiqueira, Been quite busy lately, I'll try updating tonight.

2022-03-27 19:19 UTC, listout commented
@rodrigosiqueira @kwy95 I've been trying to figure out a way to fix this rebase. All I did was `git rebase` and manually edit the conflicts. 

I'm only familiar with the basics of git any advice would be appreciated.

2022-04-09 12:13 UTC, kwy95 commented
@listout Hi, sorry for the delayed response, life and work have taken most of my time recently. To fix this PR you can follow these steps:
```bash
 # First fix the commit so it doesn't have those unwanted changes
git reset HEAD~1 # this removes the last commit but the changes are left as unstaged
git add tests/explore_test.sh # add only the relevant file to be committed
git commit # make the desired commit
 # now to remove the unwanted changes you can do
git checkout -- .
 # at this point your branch should be clean and with the desired commit at the tip
 # you can now rebase to update it
git fetch upstream # this gets the latest version of kw
git rebase -i upstream/unstable # this initiates the rebase on top of the unstable branch
 # pick your commit and execute the rebase
 # if there are any conflicts resolve them
 # at this point you should only need to update the github version, so:
git push --force # make sure your branch looks like you want it to as this overwrites the remote
```

2022-04-16 13:44 UTC, rodrigosiqueira commented
Hi,
I fixed this issue and merged it with the unstable branch.
Thanks

2022-04-16 13:44 UTC, closed without merging