src: kwlib: check if the context is inside a git worktree
kworkflow/kworkflow pull request #602
Opened 2022-04-27 19:19 UTC by mairacanal

In the functions get_git_config_regex and get_all_git_config, git produce an
error when kw mail -l is running outside a git worktree.

In order to avoid such error, the git config function checks if the context
is inside a git worktree and changes the scope to global.

Closes #551 

Signed-off-by: Maíra Canal <maira.canal@usp.br>

2022-04-27 19:44 UTC, mairacanal commented
Looking at the unit tests, I believe it is needed to understand the expected behavior. It is wanted to exit the command when it is outside a git worktree or it is wanted to display the global information?

2022-04-30 12:52 UTC, rodrigosiqueira requested changes
Hi @mairacanal ,
Thanks a lot for this PR!

I added just one inline comment. However, notice that the test `test_get_all_git_config` does not pass after your change because you change the behavior of `test_get_all_git_config`. Please update the old test and make sure that we have a test that covers the case where we are in a git tree and outside it.

@kwy95 You probably want to review this as well.
Thanks

2022-04-30 12:52 UTC, rodrigosiqueira commented on src/kwlib.sh
> +  if [[ ! $($inside_git_repo 2> /dev/null) ]]; then
We already have a function for handling this check; look at `is_inside_work_tree`. If you use it, you can delete `inside_git_repo` variable and change this conditional to something like:
`if ! is_inside_work_tree; then`

2022-04-30 13:48 UTC, kwy95 requested changes
My current review I exactly as @rodrigosiqueira 's, try to use the function we already have. Otherwise this looks good.

2022-05-06 14:06 UTC, mairacanal commented
This shellcheck failure is kind of problematic for the code's proper functioning because the function's $1 does not mean the script's $1. Have you got any suggestions on how to silence this warning?

2022-05-21 12:14 UTC, rodrigosiqueira commented
@mairacanal, why not pass `flag` as a parameter?

2022-05-21 13:01 UTC, mairacanal commented
If `flag` is passed as a parameter, I have a couple of problems with the TEST_MODE flag on the unit tests. I am not sure why, but the indentation seems to change on the output.

```test_get_all_git_config
ASSERT:line 565: Testing command expected:<git rev-parse --is-inside-work-tree &> /dev/null
global	git config --get-all --global test-config
local	git config --get-all --local test-config> but was:<global	git config --get-all --global test-config
local	git config --get-all --local test-config>
ASSERT:line 569: Testing command expected:<git rev-parse --is-inside-work-tree &> /dev/null
local	git config --get-all --local test-config> but was:<local	git config --get-all --local test-config>
ASSERT:line 575: Testing command expected:<git rev-parse --is-inside-work-tree &> /dev/null
global	git config --get-all --global test-config> but was:<global	git config --get-all --global test-config>
test_get_git_config_regex
ASSERT:line 619: Testing command expected:<git rev-parse --is-inside-work-tree &> /dev/null
global	git config --get-regexp --global 'test-config'
local	git config --get-regexp --local 'test-config'> but was:<global	git config --get-regexp --global 'test-config'
local	git config --get-regexp --local 'test-config'>
ASSERT:line 623: Testing command expected:<git rev-parse --is-inside-work-tree &> /dev/null
local	git config --get-regexp --local 'test-config'> but was:<local	git config --get-regexp --local 'test-config'>
ASSERT:line 629: Testing command expected:<git rev-parse --is-inside-work-tree &> /dev/null
global	git config --get-regexp --global 'test-config'> but was:<global	git config --get-regexp --global 'test-config'>
```

As far as user experience, the use of the `flag` parameter seems to keep everything running as expected. 

Do you have any idea on this flag issue?

2022-05-21 14:14 UTC, kwy95 commented
@mairacanal Just add this line to the top of both ifs: `# shellcheck disable=2119` :)

2022-05-27 17:56 UTC, rodrigosiqueira commented
Merged! Thanks

2022-05-27 17:56 UTC, closed without merging