src: kernel_config_manager: fix `kw --save | -s` behavior when `git commit` fails #696
kworkflow/kworkflow pull request #697
Opened 2022-09-23 06:31 UTC by davidbtadokoro

After this patch, failing `kw --save | -s` because of error in commiting save operation of .config file no longer throws wrong error (undefined function) neither consolidates the operation.

Closes: #696

2022-09-24 14:11 UTC, rodrigosiqueira requested changes

2022-09-24 14:11 UTC, rodrigosiqueira commented on src/kernel_config_manager.sh
> +    complain "Could not save user config files"
Nice catch! Since we are here, could you replace those double quotes with single quotes?

2022-09-24 14:11 UTC, rodrigosiqueira commented on src/kernel_config_manager.sh
> +    git reset --hard # Aborts save operation
If you are fixing a bug, we need a test that reproduces the issue. However, see my comment on the issue that you created; maybe we can take a different path here.

2022-10-04 12:50 UTC, rodrigosiqueira commented
Hi @davidbtadokoro , could you reduce the total of commits to just 3?
* Commit to replacing fail to complain
* One commit for the cosmetic changes
* One commit for the fix

2022-10-04 15:20 UTC, davidbtadokoro commented
For sure @rodrigosiqueira 
Thought of squashing some of those commits, but for the sake of organization I'm going to close this PR and create a clone of it.

2022-10-04 15:51 UTC, closed without merging