src: diff: implement feature to diff folders in kw
kworkflow/kworkflow pull request #709
Opened 2022-09-27 03:55 UTC by emanuellima1

This commit implements a diff on folders that shows the files on the first target that are not on the other.

kw diff folder-one folder-two

Closes #661

Signed-off-by: Emanuel Lima <emanuel-lima@outlook.com>

2022-09-29 21:58 UTC, rodrigosiqueira requested changes

2022-09-29 21:58 UTC, rodrigosiqueira commented on src/diff.sh
> +  if [[ -d $target_1 && -d $target_2 ]]; then
Add double quotes around the bash variable.

2022-09-29 21:58 UTC, rodrigosiqueira commented on src/diff.sh
> +  diff_cmd="diff --color=always -rq"
Replace `-r`with `--recursive` and `-q` with `--brief`.

2022-09-29 21:58 UTC, rodrigosiqueira commented on src/diff.sh
> +  flag=${flag:-''}
Let's add SILENCE by default.

2022-09-29 21:58 UTC, rodrigosiqueira commented on src/diff.sh
> +    complain "Make sure that $folder_1 and $folder_2 are valid folders"
For string concatenation:
https://kworkflow.org/content/codingstyle.html#string-concatenation

2022-09-29 21:58 UTC, rodrigosiqueira commented on tests/diff_test.sh
> +  assertEquals "($LINENO) Expected 22" "22" "$ret"
You don't need `$ret`, use `$?` directly.

2022-09-29 21:58 UTC, rodrigosiqueira commented on tests/diff_test.sh
> +  assertEquals "($LINENO) Expected 22" "22" "$ret"
You also don't need double quotes around 22.

2022-09-29 21:58 UTC, rodrigosiqueira commented on tests/diff_test.sh
> +}
Could you add some tests for valid cases? You can create some fake folders and test the function by calling it and comparing the output.

2022-10-03 19:36 UTC, emanuellima1 commented on src/diff.sh
> +  flag=${flag:-''}
I'm not sure what you mean by SILENCE

2022-10-04 12:52 UTC, rodrigosiqueira commented
Hi @emanuellima1 , any update here?

2022-10-04 14:29 UTC, emanuellima1 commented
> Hi @emanuellima1 , any update here?

Writing the tests now

2022-10-20 20:33 UTC, emanuellima1 commented
Is there anything else to be done on this PR?

2022-10-21 06:34 UTC, kwy95 requested changes

2022-10-21 06:34 UTC, kwy95 commented on src/diff.sh
> +  if [[ -d "$target_1" && -d "$target_2" ]]; then
Don't add commits fixing problems that were introduced in this PR, you should squash this commit with the previous one. You should only ever create extra commits to fix things that have already been merged to the main branch as you don't want to alter the history, but on PRs you should definetly adapt the commits as to make them "perfect".

2022-10-22 13:08 UTC, rodrigosiqueira requested changes

2022-10-22 13:08 UTC, rodrigosiqueira commented on src/diff.sh
> +    return 0
`diff_folders` might return a failure status code, also return it instead of return 0; i.e., `return "$?"`.

2022-10-22 13:08 UTC, rodrigosiqueira commented on src/diff.sh
> +# @flag How to display a command, see `src/kwlib.sh` function `cmd_manager`
Document the return values.

2022-10-22 13:08 UTC, rodrigosiqueira commented on src/diff.sh
> +  diff_cmd="diff --color=always --recursive --brief"
Use single-quotes here.

2022-10-22 13:08 UTC, rodrigosiqueira commented on tests/diff_test.sh
> +  local folder_2="$SAMPLES_DIR/first_set_of_bytes_from_disk"
https://kworkflow.org/content/codingstyle.html#string-concatenation

2022-10-22 13:08 UTC, rodrigosiqueira commented on tests/diff_test.sh
> +  assertEquals "($LINENO) Expected 22" 22 "$?"
Split these feature tests into two parts, let's say:
```bash
test_diff_folder_invalid_path()
...
test_diff_folder()
```
Additionally, add a test of two files that have no difference.

2022-10-24 20:13 UTC, emanuellima1 commented
I think this does it. I had to force push to squash the commits.

2022-10-26 10:18 UTC, rodrigosiqueira commented on tests/diff_test.sh
> +  output=$(LANG=en_US.UTF-8 diff_folders "$folder_1" "$folder_2")
I did not get yet why we need `LANG=en_US.UTF-8`.

2022-11-10 14:12 UTC, rodrigosiqueira commented
Hi @emanuellima1 , this change lgtm but could you address my question about the LANG?

2022-11-10 14:15 UTC, emanuellima1 commented
> Hi @emanuellima1 , this change lgtm but could you address my question about the LANG?

I thought I had addressed it. Without it the test will potentially give a false negative.

2022-11-10 14:26 UTC, rodrigosiqueira commented
> > Hi @emanuellima1 , this change lgtm but could you address my question about the LANG?
> 
> I thought I had addressed it. Without it the test will potentially give a false negative.

But why? If this is something important, we might consider adding it inside `diff_folders` function instead of adding it in the test. The idea of changing a function behavior in the test does not sound good to me since it looks like the change only focuses on making the test pass.

2022-11-10 15:37 UTC, emanuellima1 commented
> But why? If this is something important, we might consider adding it inside `diff_folders` function instead of adding it in the test. The idea of changing a function behavior in the test does not sound good to me since it looks like the change only focuses on making the test pass.

I wrote the why above:

> As I said above, I am using LANG to force the output of diff to be in english so that the test can pass no matter the language of the tester's system. Because the test is a string comparison, if the tester's machine is in Japanese, the test would fail, even though the function is working correctly.

That is why I don't think it should be inside diff_folders. We can't alter the language of a regular use of the software.

2022-11-15 12:55 UTC, rodrigosiqueira commented
Merged.
Thanks

2022-11-15 12:55 UTC, closed without merging