src: remote: fix error message thrown when `kw ssh` fails using a remote config file
kworkflow/kworkflow pull request #711
Opened 2022-09-28 04:03 UTC by davidbtadokoro

This patch corrects the error message when a failed `kw ssh` occurs using a remote config file instead of explicitly typing the IP, user and port of the host (using `kw ssh --remote | -r`). It also adds a test to verify if the correct error message is being thrown to the user in three distinct cases:
- Explicitly typing the IP, user and port;
- Using a remote config file;
- When no remote config file is found (without explicitly declaring the host infos).

Closes #695

2022-09-28 12:55 UTC, rodrigosiqueira commented
Hi @davidbtadokoro ,
 Could you rebase your change in the latest code from the unstable branch?

2022-09-28 16:11 UTC, davidbtadokoro commented
Thanks for noticing @rodrigosiqueira !
Doing it now!

2022-09-29 20:03 UTC, davidbtadokoro commented
Noticed that there are no tests for the `is_ssh_connection_configured()` function.

Also, when no remote config file is found (without explicitly defining the host with `kw ssh -r`) `kw ssh` tries anyway to establish a connection, resulting in a `Bad port '@'` thrown to the user.

Me and @pomba123 are creating tests for this function and fixing this issue of trying to connect anyway when we already know that the connection is going to fail.

2022-09-30 03:33 UTC, kwy95 requested changes
The biggest takeaway is that you should keep your commits as atomic as possible, firstly by ensuring that all the changes in the commit are necessary to achieve the commits purpose, and nothig else. But also, ensure that all tests and functionality works at every commit, so that the tool could be used at any point of it's history.

2022-09-30 03:33 UTC, kwy95 commented on src/remote.sh
> +      return 2 # ENOENT
Again, you implemented a test that expects this behavior before this behavior was implemented. As I said, you shouldn't introduce broken tests on a commit.

2022-09-30 20:23 UTC, davidbtadokoro commented
Many thanks for the feedback @kwy95 !!

It makes sense, the tool should work at any point. I actually made the fixes before the tests, but idk why I thought it was best to commit the tests before 😭

Also, thanks for pointing the other improvements.
I think I am going to close this PR and make 2 others (of one commit each to correct the failure message bug and the error handling) to clean the messy git history.

2022-10-01 20:44 UTC, closed without merging