Add an option to display all available remotes
kworkflow/kworkflow pull request #739
Opened 2022-11-16 13:02 UTC by WLAraujo

A command to list all the available remotes was added to the remote command
https://github.com/kworkflow/kworkflow/issues/729

2022-11-17 12:16 UTC, rodrigosiqueira requested changes
Hi,
I added some comments. Please, also add unit tests to this PR.

2022-11-17 12:16 UTC, rodrigosiqueira commented on src/kw_remote.sh
> +    '  remote (--list | -l) - List all the remotes'
This commit should be squashed in the previous one.

2022-11-17 12:16 UTC, rodrigosiqueira commented on src/kw_remote.sh
> +  if [[ "$1" =~ -l|--list ]]; then
The correct way to handle parameters is inside the parser function `parse_config_options`. Here, you should check for `options_values` variable.

2022-11-17 12:16 UTC, rodrigosiqueira commented on src/kw_remote.sh
> +    if [[ -f "local_remote_config_file" ]]; then
I think you forget the `$` in front of this variable.

2022-11-17 12:16 UTC, rodrigosiqueira commented on src/kw_remote.sh
> +      echo "There are no remotes"
If you are not concatenating any bash variable, just use single-quotes.

2022-11-17 12:16 UTC, rodrigosiqueira commented on src/kw_remote.sh
> +    '  remote (--list | -l) - List all the remotes'
I think this should also be the default behavior for `kw config`.

2022-11-23 13:58 UTC, rodrigosiqueira commented
Please, rebase this change against the latest unstable branch and update this PR.

2022-12-03 12:30 UTC, rodrigosiqueira requested changes
See my inline comments, and also update the commit message (use `git log src/kw_remote.sh` if you need some references).

I recommend you to read this page:
https://cbea.ms/git-commit/

2022-12-03 12:30 UTC, rodrigosiqueira commented on report_output
> +# Report:
Why this file is here?

2022-12-03 12:30 UTC, rodrigosiqueira commented on src/kw_remote.sh
> +function list_remotes()
Please, add documentation on top of this function. Check `deploy.sh` for a reference.

2022-12-03 12:30 UTC, rodrigosiqueira commented on src/kw_remote.sh
> +  if [ -f "$local_remote_config_file" ]; then
Please, use `[[` instead of `[`.

2022-12-03 12:30 UTC, rodrigosiqueira commented on src/kw_remote.sh
> +    cat $local_remote_config_file
Just `cat` a file does not look good. Let's copy `git remote -v` output, something like:
```
$kw remote --list
  origin root@something *
  ubu-tm root@anotherip
  arch-tm root@anotherxpto
```

In other words, you need to process this data a little bit.

2022-12-03 12:30 UTC, rodrigosiqueira commented on src/kw_remote.sh
> +    echo "There are no remotes"
Please, don't use `echo` refer to https://kworkflow.org/content/codingstyle.html#use-printf-instead-of-echo

2022-12-03 12:30 UTC, rodrigosiqueira commented on src/kw_remote.sh
> +    exit 0
prefer return.

2022-12-03 12:30 UTC, rodrigosiqueira commented on src/kw_remote.sh
> +      list)
You need to add `list` to the `long_options` variable. You also need to update the `bash_autocomplete.sh`.

2022-12-03 12:30 UTC, rodrigosiqueira commented on src/kw_remote.sh
> +    '  remote list - List all the remotes' \
We can use `--list` here.

2022-12-03 12:30 UTC, rodrigosiqueira commented on tests/kw_remote_test.sh
> +
Please, add tests that cover all the new code.

2022-12-09 15:19 UTC, rodrigosiqueira commented
@WLAraujo any update here?

2022-12-11 13:58 UTC, rodrigosiqueira commented
Hi @WLAraujo , please address my previous comments and take a look at some of the links that I shared with you.

2022-12-11 18:13 UTC, WLAraujo commented
Hi @rodrigosiqueira!
Sorry it took me so long to get back to you.
I'll try to take a look at the comments and make the changes today.

2022-12-18 14:25 UTC, rodrigosiqueira commented
@WLAraujo could you address my previous comments and fix the shellcheck failure?

2022-12-29 14:06 UTC, rodrigosiqueira commented
I closed this PR due to the lack of reply. If you have a better version of this change, feel free to re-open this PR.

2022-12-29 14:06 UTC, closed without merging