src: kw_env: Adding support to `kw env --no-env`
kworkflow/kworkflow pull request #758
Opened 2022-12-30 05:04 UTC by aquilamacedo

This commit creates a mechanism allowing the user to "exit" the env resource using the `--no-env` parameter.

Closes: #746

Signed-off-by: Aquila Macedo <aquilamacedo@riseup.net>

2022-12-30 05:20 UTC, aquilamacedo commented
Hi @rodrigosiqueira. I just created this draft issue #746. I would like to know if the implementation is according to your specifications.

2022-12-30 20:48 UTC, rodrigosiqueira requested changes

2022-12-30 20:48 UTC, rodrigosiqueira commented on documentation/man/features/env.rst
> +  Allow users to "exit" the env feature.
After reading this, I think that `--exit-env` is a better name.

2022-12-30 20:48 UTC, rodrigosiqueira commented on documentation/man/features/env.rst
> +  Allow users to "exit" the env feature.
Also, explain what exit an env means. Explain the behavior as we discussed in the https://github.com/kworkflow/kworkflow/issues/746 .

2022-12-30 20:48 UTC, rodrigosiqueira commented on documentation/man/features/env.rst
> +If you want to exit the env feature:::
Delete one of the `:`

2022-12-30 20:48 UTC, rodrigosiqueira commented on src/kw_env.sh
> +function use_no_env()
add function documentation, and let's call this function `exit_env`.

2022-12-30 20:48 UTC, rodrigosiqueira commented on src/kw_env.sh
> +  if [[ $(ask_yN 'Do you want to make this env the default?') =~ '1' ]]; then
I think you can add a warning followed by the question, something like:
```
warning 'You are about to leave the env setup, and ENV_NAME config files will be used as a default.'
  if [[ $(ask_yN 'Do you really want to proceed?') =~ '1' ]]; then
```

2022-12-30 20:48 UTC, rodrigosiqueira commented on src/kw_env.sh
> +      if [[ -L "${local_kw_configs}/${config}.config" ]]; then
Add a comment before this `if` that explains that you are removing the link but not the original file.

2022-12-30 20:48 UTC, rodrigosiqueira commented on src/kw_env.sh
> +    printf '%s\n' 'NO ENV' > "${local_kw_configs}/${ENV_CURRENT_FILE}"
I think you can remove the current env file.

2022-12-30 20:48 UTC, rodrigosiqueira commented on src/kw_env.sh
> +    success "You left the environment feature."
single quotes.

2023-01-06 18:10 UTC, aquilamacedo commented
Hi @rodrigosiqueira. I just finished making the requested changes :)

2023-01-08 15:00 UTC, rodrigosiqueira commented
Thanks a lot for this PR. I already merged it with the following changes:

```bash
diff --git a/src/bash_autocomplete.sh b/src/bash_autocomplete.sh
index 64941a3..e5a01da 100644
--- a/src/bash_autocomplete.sh
+++ b/src/bash_autocomplete.sh
@@ -70,7 +70,7 @@ function _kw_autocomplete()
   kw_options['drm']='--remote --local --gui-on --gui-off --load-module
                      --unload-module --conn-available --modes --help'
 
-  kw_options['env']='--create --list --use'
+  kw_options['env']='--create --list --use --exit-env'
 
   kw_options['self-update']='--unstable --help'
   kw_options['u']="${kw_options['self-update']}"
diff --git a/src/kw_env.sh b/src/kw_env.sh
index ef42135..4163aa6 100644
--- a/src/kw_env.sh
+++ b/src/kw_env.sh
@@ -86,7 +86,7 @@ function exit_env()
 
   current_env=$(< "${local_kw_configs}/${ENV_CURRENT_FILE}")
 
-  warning 'You are about to leave the env setup, and ENV_NAME config files will be used as a default.'
+  warning "You are about to leave the env setup, and ${current_env} config files will be used as a default."
   if [[ $(ask_yN 'Do you really want to proceed?') =~ '1' ]]; then
     for config in "${config_file_list[@]}"; do
       # All symbolic links will be removed, and the current env configuration files
```

2023-01-08 15:00 UTC, closed without merging