src: build: standardize build.sh file.
kworkflow/kworkflow pull request #788
Opened 2023-03-07 22:55 UTC by aquilamacedo

In order to follow the pattern of other kw files, this commit
organizes the order of functions in the `build.sh` file.

Closes: #787

2023-03-07 23:58 UTC, rodrigosiqueira requested changes
lgtm, but fix the CI failures.

2023-03-12 23:10 UTC, aquilamacedo commented
> lgtm, but fix the CI failures.

I'm trying to fix this error in the CI. According to review-dog, the problem is on line 743, but I don't understand the reason for the error.

![image](https://user-images.githubusercontent.com/43859386/224579148-c8a060ce-f312-418d-9a33-3f61fed522c8.png)

2023-03-14 17:41 UTC, rodrigosiqueira commented
Please, check:
https://github.com/koalaman/shellcheck/wiki/SC2317

I guess `build_kernel_main` has an exit.

2023-03-19 00:42 UTC, aquilamacedo commented
Hi @rodrigosiqueira. I figured out what the problem was and fixed it. It had a duplicate function and two functions with the same name; I don't know how this code got past CI before. It is now working correctly!

2023-03-21 13:38 UTC, rodrigosiqueira commented
Merged, thanks.

2023-03-21 13:38 UTC, closed without merging