Added support for gentoo (Local deployment only)
kworkflow/kworkflow pull request #822
Opened 2023-03-19 08:44 UTC by siddhanthrathod

2023-03-21 13:20 UTC, rodrigosiqueira requested changes
In lgtm, but I want to see tests and remote deploy support.

2023-03-21 14:43 UTC, siddhanthrathod commented on documentation/dependencies/gentoo.dependencies
Okay

2023-03-21 14:45 UTC, siddhanthrathod commented on src/plugins/kernel_install/gentoo.sh
> +    cmd="sudo -E $cmd"
sorry will do

2023-03-21 14:46 UTC, siddhanthrathod commented
Okay I will do that

2023-04-10 17:44 UTC, rodrigosiqueira commented
Any update here?

2023-04-18 23:52 UTC, rodrigosiqueira commented
I'm closing this PR. If you have a new version, please re-open it.

2023-04-18 23:52 UTC, closed without merging