Fix kw init wrong template name
kworkflow/kworkflow pull request #838
Opened 2023-04-26 21:12 UTC by aquilamacedo

Do not prepend ':' to the template name. Previously, it was required
to set a default template when the `--template` option was not used.
However, this is no longer necessary.

Closes https://github.com/kworkflow/kworkflow/issues/748

2023-05-13 15:35 UTC, rodrigosiqueira requested changes

2023-05-13 15:35 UTC, rodrigosiqueira commented on documentation/man/features/init.rst
> +-v, \--verbose:
We decided not to support `-v`, please remove it.

2023-05-13 15:35 UTC, rodrigosiqueira commented on src/init.sh
> +  flag=${flag:-'SILENT'}
How about:
```bash
flag=${flag:-'SILENT'}
[[ -n "${options_values['VERBOSE']}" ]] && flag='VERBOSE'
```

2023-05-13 15:35 UTC, rodrigosiqueira commented on src/init.sh
> +  cmd="mkdir --parents \"${PWD}/${KW_DIR}\""
I don't think you need to add `"` inside `"`. In other words, drop the internal quotes for command and the other.

2023-05-13 15:35 UTC, rodrigosiqueira commented on documentation/man/features/init.rst
> -| *kw* *init* [(-v | \--verbose)] [\--arch <name>][\--remote <user>@<ip>:<port>][\--target <target>]
You don't need this extra commit for that; go back to the previous commit and just remove `-v` from there.

2023-05-17 20:46 UTC, aquilamacedo commented
Hi @rodrigosiqueira. Actually, those changes you asked for were already made in the last commit.

2023-05-17 23:44 UTC, rodrigosiqueira commented
@aquilamacedo  squash your last commit with the previous one.

2023-05-19 21:47 UTC, rodrigosiqueira commented
Merged!
Thanks a lot

2023-05-19 21:47 UTC, closed without merging