src: lib: dialog_ui: Add create form function
kworkflow/kworkflow pull request #876
Opened 2023-06-24 15:21 UTC by rodrigosiqueira

Dialog provides support for creating simple forms. This commit a function to make it easy to create new forms.

2023-06-24 18:13 UTC, davidbtadokoro commented
Hi @rodrigosiqueira, thanks for this change.
Going to look carefully at it as soon as possible.

2023-06-24 19:06 UTC, davidbtadokoro requested changes
Thanks a lot, @rodrigosiqueira!
This screen surely will be handy all across the project. Made some comments, feel free to ping me with any doubts.

2023-06-24 19:06 UTC, davidbtadokoro commented on src/lib/dialog_ui.sh
> +  # Creating form line
Maybe 'Adding form option' or 'Add form option'?

2023-06-24 19:06 UTC, davidbtadokoro commented on src/lib/dialog_ui.sh
> +  # Change cancel label
Maybe 'Override OK and Cancel labels'? Either way, you are also changing the 'OK' label.

2023-06-24 19:06 UTC, davidbtadokoro commented on src/lib/dialog_ui.sh
> +  # Find out the largest label to know where we need to start the field
Maybe /need to start the field/need to start the **input** field/ ?

2023-07-17 23:24 UTC, rodrigosiqueira commented
Hi @davidbtadokoro ,
I addressed all your comments. Thanks a lot for your review.

2023-08-02 02:25 UTC, davidbtadokoro approved these changes
Hi @rodrigosiqueira
Thanks for the update. It looks really nice to me 👍

2023-08-02 14:43 UTC, closed without merging