src: mail: Add 'additional_emails' configuration
kworkflow/kworkflow pull request #909
Opened 2023-09-06 06:00 UTC by davidbtadokoro

`kw mail` already has a configuration to automatically block emails as recipients named 'blocked_emails'. An opposite configuration, to automatically add emails as recipients doesn't exist, though.

In this context, add the configuration 'additional_emails' to `kw mail` to automatically add pre-determined recipients.

2023-09-06 14:13 UTC, rodrigosiqueira requested changes
In general, it lgtm. Remember to add a test and reference @melissawen issue in the commit message. Also, expand the man documentation.

2023-09-06 14:13 UTC, rodrigosiqueira commented on etc/mail.config
> +additional_emails=
I don't think this field expresses the idea behind it really well. Maybe we can try something like `demails_always_included` (it is still a bad name, it is just an example)...

We also should have one for `to` and another one for `cc`.

2023-09-07 17:17 UTC, davidbtadokoro commented
Hey @rodrigosiqueira, thanks for the feedback!
I updated the PR addressing your comments.
In respect to the configurations name, I used `default_to_recipients` and `default_cc_recipients`. What do you think?

2023-09-07 17:44 UTC, melissawen commented
names sounds good to me.

2023-09-09 13:54 UTC, rodrigosiqueira commented
Overall, it lgtm. @melissawen I'll wait for your okay for this change before I merge it.

2023-09-13 09:38 UTC, melissawen commented
Just tested and it works as expected. I noticed that when I add the same e-mail address to `default_to_recipients` and `default_cc_recipients` it doesn't repeat and the list of e-mails in `To:` is prioritized. All good, you can add my t-b:
melissa.srw \<at\> gmail.com

2023-09-15 13:03 UTC, closed without merging