`run_tests`: fix tests on non-english machines
kworkflow/kworkflow pull request #926
Opened 2023-09-25 21:45 UTC by jooag

On machines with non-english locales, some error messages generated are printed in that language. The tests assertions, thus, fail inappropriately. In this context, set LANGUAGE environment variable before running the tests.

Closes #916.

2023-09-26 22:11 UTC, rodrigosiqueira commented
@davidbtadokoro

2023-09-27 01:49 UTC, davidbtadokoro requested changes
This is really a great catch! Thanks @jooag and @GuilhermeMoreno.

Aside from my inline comment that I left, in the commit message header, you used \` in \`run_tests\`: fix [...]. See if you can remove it.

At last, don't forget to add the `Signed-off-by` tag (see https://kworkflow.org/content/howtocontribute.html#certify-your-work-by-adding-your-signed-off-by-line)

Nevertheless, tested it and it worked! Although it is a small change it has a great impact 👍

2023-09-27 01:49 UTC, davidbtadokoro commented on run_tests.sh
> +  LANGUAGE=en_US.UTF_8 run_tests
You also need to do this in line 122 to avoid single test runs like

```bash
./run_tests.sh test kwlib_test
```

from failing.

2023-10-02 04:43 UTC, davidbtadokoro approved these changes
Hey @jooag and @GuilhermeMoreno, and thanks for the update.

I have just 3 minor nitpicks about the commit message:
1. Try breaking line in the commit message body to avoid surpassing 72 characters;
2. Don't add a blank line between the `Co-authored-by` and `Signed-off-by`;
3. I think (@rodrigosiqueira can verify this) you don't need to use `Co-authored-by` for the same person that is referenced in the `Signed-off-by`.

Fixed those as they are really small nitpicks, but don't forget to mind those in the future.

Nevertheless, everything LGTM, so, merged into the unstable : )

2023-10-02 04:45 UTC, closed without merging