src: build: Fix cflags formatting issue
kworkflow/kworkflow pull request #943
Opened 2023-10-23 14:52 UTC by aquilamacedo

This commit solves the issue where setting the string as cflags "-DAMD_PRIVATE_COLOR" was not functioning as expected. The code has been updated the code to properly escape the minus symbol in cflags, making it work as expected

Closes: #934

2023-10-23 14:54 UTC, aquilamacedo commented
@melissawen, I made a PR related to the issue you had opened, could you review it for me?

2023-10-23 16:57 UTC, davidbtadokoro commented
Hey @melissawen, if you want, you can leave the code review to me. However, I feel like we need your greenlight for the behavior, as you opened the issue and surely knows much more about the domain.

2023-10-23 19:05 UTC, aquilamacedo commented
@davidbtadokoro and @rodrigosiqueira, if you have any comments, your feedback would be more than welcome too. :)

2023-10-29 21:16 UTC, davidbtadokoro requested changes
Hi @aquilamacedo, and thanks for tackling this issue.

I have no inline comments. However, you claim to be escaping the minus `-` symbol, but it seems to me that what you are actually doing is surrounding the `cflags` value with double-quotes (e.g., `KCFLAGS="-DAMD_PRIVATE_COLOR"`). In case in not misunderstanding things, it may be best to change the commit message to express this.

Other than that, I tried reproducing the bug reported in #934, and this PR seems to fix it 👍

In any case, I feel that the greenlight of @melissawen is a must.

2023-11-03 15:05 UTC, aquilamacedo commented
Hi @davidbtadokoro. Thx for your review :). I've updated the commit message to provide a more accurate description of the changes. Could you please verify if everything is in order now?

2023-11-03 16:24 UTC, davidbtadokoro reviewed
Hi @aquilamacedo! Read you updated commit message and it looks great to me 👍 

As I tested the behaviour in the last review and the code looks good, lets just wait for Melissa's greenlight to merged it 😬

2023-11-06 21:56 UTC, melissawen commented
Just tested it. All good! Thank you guys for fixing the issue and reviewing.

2023-11-07 17:39 UTC, closed without merging

2023-11-07 17:39 UTC, davidbtadokoro commented
Hi @melissawen and thanks for testing it! @aquilamacedo, since everything seems OK, I merged your PR into the unstable. Thanks 👍