Add verbose to debug
kworkflow/kworkflow pull request #958
Opened 2023-11-10 02:06 UTC by rodrigosiqueira

2023-11-18 02:06 UTC, davidbtadokoro requested changes
Hey @rodrigosiqueira, thanks so much for this verbose change!

Left some comments so see if you can address them.

As a side note, I tested the verbose behaviour, but don't really know how to use the `kw debug` feature to test it further than `kw debug --list`. Can you mention some commands for me to test?

2023-11-18 02:06 UTC, davidbtadokoro commented on src/lib/kwlib.sh
> +}
Think it is worth adding a simple unit test for this.

2023-11-18 02:06 UTC, davidbtadokoro commented on src/debug.sh
> +    reset_debug "$target" "$flag"
Can't we squash this commit with the previous one?

2023-11-18 17:25 UTC, rodrigosiqueira commented
> Hey @rodrigosiqueira, thanks so much for this verbose change!
> 
> Left some comments so see if you can address them.
> 
> As a side note, I tested the verbose behaviour, but don't really know how to use the `kw debug` feature to test it further than `kw debug --list`. Can you mention some commands for me to test?

Thanks, I'll update the PR.

Btw, we have a tutorial for this:

https://kworkflow.org/tutorials/kernel-debug.html

2023-11-21 01:22 UTC, aquilamacedo commented on src/lib/kwlib.sh
> +  [[ "$flag" == 'VERBOSE' ]] && printf '%s\n' "$cmd"
Wouldn't it be better to use `say "$cmd"` here? It would ensure that the output adheres to the blue color standard of the verbose mode.

2023-11-25 17:14 UTC, rodrigosiqueira commented
@davidbtadokoro @aquilamacedo Thanks for your feedback. I updated this PR based on your suggestions.

2023-11-27 21:29 UTC, davidbtadokoro commented
Thanks for the update @rodrigosiqueira! Merged into the unstable branch.

2023-11-27 21:29 UTC, closed without merging