`patch-hub`: Move function `handle_exit` and update documentation
kworkflow/kworkflow pull request #959
Opened 2023-11-11 16:22 UTC by davidbtadokoro

The function `handle_exit` used by `patch-hub` Controller component to stop the execution of the FSM is:

1. Implemented in a out-of-place way, inside `src/lib/dialog_ui.sh`. It fits better inside the file `src/ui/patch_hub/patch_hub_core.sh`;
2. Has a misleading documentation stating it is used to handle the exit of Dialog (View component).

This PR introduces two commits that try to address these issues.

2023-11-12 19:08 UTC, rodrigosiqueira requested changes

2023-11-12 19:08 UTC, rodrigosiqueira commented on src/lib/dialog_ui.sh
hmmm... I don't agree with this change... I was working on a draft of the visual setup of `kw init` which uses dialog. With this change, I'll need to include `patch_hub_core.sh`, which does not make sense to me.

2023-11-13 00:16 UTC, davidbtadokoro commented on src/lib/dialog_ui.sh
After reading your comment, I'm with you on that. `handle_exit` is a function to be used in other UIs. That being said, I don't think the function fits `src/lib/dialog_ui.sh` neither. What do you say to moving it to `kwlib.sh` or createing a lib function in `src/ui` for UIs?

2023-11-16 00:23 UTC, rodrigosiqueira commented on src/lib/dialog_ui.sh
> That being said, I don't think the function fits src/lib/dialog_ui.sh neither.

But I think the error codes inside this function and the `clear` are particular behaviors associated with the dialog.

2023-11-17 17:00 UTC, closed without merging