src: lib: lore: Fix duplication when listing patchsets
kworkflow/kworkflow pull request #964
Opened 2023-11-15 23:50 UTC by JGBSouza

Listing patches off any mailing list could result in duplicate patches being displayed unnecessarily.

In this sense, solve the problem by checking if the patch already has been processed.

This PR resolves #914

2023-11-18 01:02 UTC, davidbtadokoro commented
Just for the record, I had an offline conversation with @JGBSouza, and I proposed some changes to his commit. The altered commit is below.

```
diff --git a/src/lib/lore.sh b/src/lib/lore.sh
index ba17d94..f38ff4b 100644
--- a/src/lib/lore.sh
+++ b/src/lib/lore.sh
@@ -63,6 +63,10 @@ declare -g MIN_INDEX=0
 # it easy to undertand.
 declare -ag list_of_mailinglist_patches
 
+# This associative array stores the current processed patchsets and it is used
+# to check if a given patchset was already processed.
+declare -Ag processed_patchsets
+
 # This function creates the directory used by kw for any lore related data.
 #
 # Return:
@@ -299,6 +303,8 @@ function reset_current_lore_fetch_session()
   list_of_mailinglist_patches=()
   PATCHSETS_PROCESSED=0
   MIN_INDEX=0
+  unset processed_patchsets
+  declare -Ag processed_patchsets
 }
 
 # This function composes a query URL to a public mailing list archived
@@ -424,13 +430,14 @@ function process_patchsets()
     if [[ "$line" =~ ^[[:space:]]href= ]]; then
       patch_url=$(str_get_value_under_double_quotes "$line")
 
-      if is_introduction_patch "$patch_url"; then
-        # Process each patch in parallel
+      if [[ "${processed_patchsets["$patch_url"]}" != 1 ]] && is_introduction_patch "$patch_url"; then
+        # Processes each patch in parallel
         thread_for_process_patch "$PATCHSETS_PROCESSED" "$shared_dir_for_parallelism" \
           "$processed_patchset" "$patch_url" "$patch_title" &
         pids[i]="$!"
         ((i++))
         ((PATCHSETS_PROCESSED++))
+        processed_patchsets["$patch_url"]=1
       fi
 
       processed_patchset=''
diff --git a/tests/lib/lore_test.sh b/tests/lib/lore_test.sh
index 7ea4a16..97aa61c 100755
--- a/tests/lib/lore_test.sh
+++ b/tests/lib/lore_test.sh
@@ -559,11 +559,16 @@ function test_reset_current_lore_fetch_session()
   list_of_mailinglist_patches[2]=1
   PATCHSETS_PROCESSED=3
   MIN_INDEX=200
+  declare -Ag processed_patchsets
+  processed_patchsets['patch_1']=1
+  processed_patchsets['patch_2']=1
+  processed_patchsets['patch_3']=1
 
   reset_current_lore_fetch_session 2
   assert_equals_helper 'Should reset `list_of_mailinglist_patches`' "$LINENO" 0 "${#list_of_mailinglist_patches[@]}"
   assert_equals_helper 'Should reset `PATCHSETS_PROCESSED`' "$LINENO" 0 "$PATCHSETS_PROCESSED"
   assert_equals_helper 'Should reset `MIN_INDEX`' "$LINENO" 0 "$MIN_INDEX"
+  assert_equals_helper 'Should reset `processed_patchsets`' "$LINENO" 0 "${#processed_patchsets[@]}"
 }
 
 function test_format_patchsets()
```

2023-11-24 16:37 UTC, JGBSouza commented
Hi @davidbtadokoro, thanks for the updates. Looking to all the changes they really seem to make the code better

2023-11-24 18:29 UTC, davidbtadokoro commented
@rodrigosiqueira @JGBSouza I came upon a possible concurrency problem. Because we process each patch in parallel, it is possible for a thread to pass the check if the patchset was processed, when it shouldn't.

For example, imagine thread 1 gets patchset of  message ID `foo`. Thread 1 enters the if statement and goes into a background to process the patchset. Until it finishes the process, assign `processed_patchsets["$patch_url"]=1` does not happen. Suppose thread 2 also gets patchset of  message ID `foo`, the thread will also enter the if statement and process the same patchset.

All this to say, do you think that this makes sense? Think I just stumbled into this behavior, but didn't screenshot 😞. Below I put the part of the code that I think the concurrency problem may happen, and added the two points I think the assign `processed_patchsets["$patch_url"]=1` should happen (the first being the one that prevents concurrency and the second being the "correct" one). What do you guys think?

```bash
-      if is_introduction_patch "$patch_url"; then
-        # Process each patch in parallel
+      if [[ "${processed_patchsets["$patch_url"]}" != 1 ]] && is_introduction_patch "$patch_url"; then
+        processed_patchsets["$patch_url"]=1 # <--- LOCK AT THE BEGINNING
+        # Processes each patch in parallel
         thread_for_process_patch "$PATCHSETS_PROCESSED" "$shared_dir_for_parallelism" \
           "$processed_patchset" "$patch_url" "$patch_title" &
         pids[i]="$!"
         ((i++))
         ((PATCHSETS_PROCESSED++))
+        processed_patchsets["$patch_url"]=1 # <--- LOCK AT THE END
       fi
```

2023-11-27 21:12 UTC, davidbtadokoro commented
> @rodrigosiqueira @JGBSouza I came upon a possible concurrency problem. Because we process each patch in parallel, it is possible for a thread to pass the check if the patchset was processed, when it shouldn't.

After offline discussion I realized that my comment did not make sense.

2023-12-09 16:33 UTC, rodrigosiqueira requested changes

2023-12-09 16:33 UTC, rodrigosiqueira commented on tests/unit/lib/lore_test.sh
Just a note about the commit message: if Joao helped to develop this change, you should not add his reviewed-by. Use Co-developed-by instead.

2023-12-09 16:33 UTC, rodrigosiqueira commented on tests/unit/lib/lore_test.sh
> +  assert_equals_helper 'Wrong processed patchset (index 2)' "$LINENO" "$expected" "${list_of_mailinglist_patches[2]}"
Add new lines in the `assert_equals_helper` areas for readability's sake. Maybe consider splitting these checks into two or more test functions?

2023-12-09 16:33 UTC, rodrigosiqueira commented on tests/unit/lib/lore_test.sh
> +  expected='David BowieÆmajor.tom@rock.ukÆXÆXÆ[RFC PATCH v12] Introduce Ziggy StardustÆhttp://lore.kernel.org/rock/introduction'
Add a new line

2023-12-09 16:33 UTC, rodrigosiqueira commented on tests/unit/lib/lore_test.sh
> +
Drop this extra line.

2023-12-09 16:33 UTC, rodrigosiqueira commented on tests/unit/lib/lore_test.sh
> +  processed_patchsets['patch_1']=1
Add new line.

2023-12-16 18:12 UTC, rodrigosiqueira commented
Hi @JGBSouza , please try to update this PR.

2023-12-23 18:57 UTC, davidbtadokoro commented
Thanks so much for the continuing working in this PR @JGBSouza! It fixed the issue and it looks legit, so merged into the unstable branch :+1:

2023-12-23 18:57 UTC, closed without merging