Add verbose mode in kw_db to show sqlite3 database commands
kworkflow/kworkflow pull request #975
Opened 2023-11-24 16:44 UTC by aquilamacedo

In certain feature functions, there's a reliance on `kw_db` functions. This commit introduces support for a verbose mode, revealing the SQL commands executed under the hood

2023-11-25 17:28 UTC, rodrigosiqueira requested changes
I added some comments to this PR; please review everything based on that.

2023-11-25 17:28 UTC, rodrigosiqueira commented on src/kernel_config_manager.sh
> +  show_verbose "$flag" "$cmd"
I think you need to reverse this order and use `SILENT` in the `select_from`.

2023-11-25 17:28 UTC, rodrigosiqueira commented on src/kernel_config_manager.sh
> +  is_on_database="$(select_from 'SILENT' "kernel_config WHERE name IS '${config_name}'")"
I think you forgot the `show_verbose`.

2023-11-25 17:28 UTC, rodrigosiqueira commented on src/kernel_config_manager.sh
> +  configs="$(select_from 'SILENT' 'kernel_config' 'name AS \"Name\", description AS \"Description\", last_updated_datetime AS \"Last updated\"' '.mode column')"
You forgot to add the `show_verbose` before this function.

2023-11-25 17:28 UTC, rodrigosiqueira commented on src/kernel_config_manager.sh
> +  show_verbose "$flag" "$cmd"
I think you need to reverse this order and use `SILENT` in the `select_from`.

2023-11-25 17:28 UTC, rodrigosiqueira commented on src/pomodoro.sh
> +  show_verbose "$flag" "$cmd"
I think you need to reverse this order and use `SILENT` in the `select_from`.

2023-11-25 17:28 UTC, rodrigosiqueira commented on src/pomodoro.sh
> +  show_verbose "$flag" "$cmd"
I think you need to reverse this order and use `SILENT` in the `select_from`.

2023-12-02 19:27 UTC, rodrigosiqueira commented
Hi @aquilamacedo , please, update this PR. This is the final part to complete the verbose task.

2024-01-05 04:12 UTC, aquilamacedo commented
Hi @rodrigosiqueira. Yes, I'm working on it, I'm trying to think of a logic to create a new functionality within `kwlib.sh`, something like a VERBOSE_DB (as in the screenshot below), it would be a good approach to show the verbose output of the `kw_db.sh` functions.

![image](https://github.com/kworkflow/kworkflow/assets/43859386/048af185-305b-4f38-8242-37a72b52273a)

However, I'm still uncertain about the best approach to initialize the 'VERBOSE_DB' value (for instance, within the 'kernel_config_manager'). This is because there already exists 'VERBOSE', which can be initialized if the --verbose argument is passed. Therefore, the flag will assume the value initialized by this line:

```
   [[ -n "${options_values['VERBOSE']}" ]] && flag='VERBOSE'
```

Integrating 'VERBOSE_DB' requires a similar strategy to ensure proper initialization that aligns with the existing code logic.

2024-01-13 18:00 UTC, rodrigosiqueira requested changes
@davidbtadokoro since you discussed with @aquilamacedo , could you review this change?

2024-01-17 16:15 UTC, davidbtadokoro commented
> @davidbtadokoro since you discussed with @aquilamacedo , could you review this change?

For sure! Sorry for the delay, starting to work on it now

2024-01-17 17:43 UTC, davidbtadokoro requested changes
Hey @aquilamacedo, sorry for the delay and thanks so much for this change. We are almost at the perfect point :+1:

2024-01-17 17:43 UTC, davidbtadokoro commented on src/pomodoro.sh
>  # Show registered tags with number identification.
Think you forgot to add verbose to `select_from` in the function `show_active_pomodoro_timebox` that `kw pomodoro --check-timer` uses underneath.

It is
![Screenshot from 2024-01-17 14-06-43](https://github.com/kworkflow/kworkflow/assets/95055784/e5ffc725-19f1-4231-b964-46d3e05532fe)


but it should be
![Screenshot from 2024-01-17 14-09-03](https://github.com/kworkflow/kworkflow/assets/95055784/76e39943-80d0-46ab-b2b6-896b02505cdf)

2024-01-17 17:43 UTC, davidbtadokoro commented on src/pomodoro.sh
>  # Show registered tags with number identification.
Also, think you forgot to add verbose to `select_from` in the function `get_tag_name`.

2024-01-23 19:06 UTC, davidbtadokoro requested changes
Hi @aquilamacedo, and thanks for updating the PR again! Left fewer and simpler comments this time :grin:

We really are getting into that perfect state, so much so that, with the greenlight of @rodrigosiqueira, I can address these comments myself and merge it into the unstable branch.

2024-01-23 21:10 UTC, aquilamacedo commented on tests/unit/lib/kwlib_test.sh
> +function test_cmd_manager_check_silent_option()
I liked this test @davidbtadokoro, I'm going to use it :)

2024-01-23 21:17 UTC, aquilamacedo commented on src/lib/kwlib.sh
> +    VERBOSE_DB)
I'm cool with the name being lengthy. It's actually good because it gives a clear picture of what it's all about.

2024-01-24 15:10 UTC, davidbtadokoro reviewed
Thanks again @aquilamacedo. IMHO, I can't see other improvments to this PR. @rodrigosiqueira, I'll wait for your greenlight.

2024-02-04 18:56 UTC, rodrigosiqueira commented
Hi, thanks a lot for keeping improving this PR!
Change merged into the unstable branch.

2024-02-04 18:56 UTC, closed without merging