setup.sh: add flag --skip-docs to skip generating man pages
kworkflow/kworkflow pull request #979
Opened 2023-12-01 18:26 UTC by uwla

With this new flag,the user can install KW without generating man pages, which takes time due to sphinx.  This  drastically  reduce  installation time and is specially useful in cases where the  manual  pages  are  not needed, such as local development and continuous integration.

2023-12-02 19:20 UTC, rodrigosiqueira reviewed
This option is not working. I tried:

```
./setup.sh --skip-docs
Invalid number of arguments
usage: ./setup.sh option

Where option may be one of the following:
--help      | -h     Display this usage message
--install   | -i     Install kw
--uninstall | -u     Uninstall kw
--skip-checks        Skip checks (use this when packaging)
--skip-docs          Skip generating man pages (use this when installing)
--verbose            Explain what is being done
--force              Never prompt
--completely-remove  Remove kw and all files under its responsibility
--docs               Build kw's documentation as HTML pages into ./build
--enable-tracing     Install kw with tracing enabled (use it with --install)
```

2023-12-02 19:20 UTC, rodrigosiqueira commented on setup.sh
> +  if [ "$arg" = '--skip-docs' ]; then
prefer `[[]]`.

2023-12-03 18:08 UTC, uwla commented
> This option is not working. I tried:
> 
> ```
> ./setup.sh --skip-docs
> Invalid number of arguments
> usage: ./setup.sh option
> 
> Where option may be one of the following:
> --help      | -h     Display this usage message
> --install   | -i     Install kw
> --uninstall | -u     Uninstall kw
> --skip-checks        Skip checks (use this when packaging)
> --skip-docs          Skip generating man pages (use this when installing)
> --verbose            Explain what is being done
> --force              Never prompt
> --completely-remove  Remove kw and all files under its responsibility
> --docs               Build kw's documentation as HTML pages into ./build
> --enable-tracing     Install kw with tracing enabled (use it with --install)
> ```

It will only work you add the flag `-i|--install` along with it.

Like one of the following:

```
$ ./setup.sh -i --skip-docs
$ ./setup.sh --install --skip-docs
$ ./setup.sh -i --skip-docs --force
$ ./setup.sh --install --skip-docs --force
```

The flag `--skip-docs` means "don't generate manpages when installing". Therefore, if you are not providing flags `-i` or `--install`, it won't work because it is not installing. Do you agree with this behavior?

2023-12-05 22:41 UTC, davidbtadokoro requested changes
Hey @uwla, and thanks for this change.

Indeed, there are some installations, specially for development and reviewing, where the man pages are not needed and, because they account for the majority of the installation time, for me it makes sense to have this option :smile:.

Overall LGTM. Tested `--install --skip-docs`, `-i --skip-docs`, `--skip-docs --install`, `--skip-docs -i`, and `--install`, and they work as expected (the first four are the same and skip the docs, while the last installs kw just like always).

Left a simple comment about style, so please  address it and the one left by @rodrigosiqueira .

2023-12-05 22:41 UTC, davidbtadokoro commented on setup.sh
> +  say '--skip-docs          Skip generating man pages (use this when installing)'
Maybe 'Skip generation of man pages' instead.

2023-12-06 01:06 UTC, davidbtadokoro approved these changes
Hey @uwla, thanks for addressing our comments. Tested again and it look legit.
@rodrigosiqueira, I'm going to wait for your greenlight on this, as this PR adds new behavior and you also reviewed it.

2023-12-06 01:30 UTC, rodrigosiqueira commented
@davidbtadokoro you can go ahead and merge it.

2023-12-06 01:53 UTC, davidbtadokoro commented
Thanks for the attention guys! Merged into the unstable branch 👍

2023-12-06 01:53 UTC, closed without merging