src: deploy: fix preparation of remote directory
kworkflow/kworkflow pull request #991
Opened 2023-12-11 14:52 UTC by jooag

If the temporary directory already existed, it would not be cleaned up. This could cause issues if multiples deploys were made without rebooting the target. In this context, the code now removes the temporary directory and creates it again.

Fixes kworkflow/kworkflow#990.

2023-12-16 18:40 UTC, rodrigosiqueira requested changes

2023-12-16 18:40 UTC, rodrigosiqueira commented on src/deploy.sh
> +  cmd_remotely "rm --preserve-root=all --recursive --force -- $KW_DEPLOY_TMP_FILE" "$flag"
https://kworkflow.org/content/codingstyle.html#string-concatenation

2023-12-16 18:40 UTC, rodrigosiqueira commented on src/deploy.sh
> +  cmd_remotely "rm --preserve-root=all --recursive --force -- $KW_DEPLOY_TMP_FILE" "$flag"
Just out of curiosity, why do we need `--`?

2023-12-16 18:40 UTC, rodrigosiqueira commented on src/deploy.sh
> +  cmd_remotely "rm --preserve-root=all --recursive --force -- $KW_DEPLOY_TMP_FILE" "$flag"
Also, always check the variable before trying to run `rm` on it since it might have the wrong path.

2023-12-16 18:40 UTC, rodrigosiqueira commented on tests/unit/deploy_test.sh
> +    "$CONFIG_SSH $CONFIG_REMOTE sudo \"rm --preserve-root=all --recursive --force -- $KW_DEPLOY_TMP_FILE\""
https://kworkflow.org/content/codingstyle.html#string-concatenation

2023-12-16 18:40 UTC, rodrigosiqueira commented on tests/unit/deploy_test.sh
> +    "$CONFIG_SSH $CONFIG_REMOTE sudo \"rm --preserve-root=all --recursive --force -- $KW_DEPLOY_TMP_FILE\""
https://kworkflow.org/content/codingstyle.html#string-concatenation

2023-12-16 18:40 UTC, rodrigosiqueira commented on tests/unit/deploy_test.sh
> +    "$CONFIG_SSH $CONFIG_REMOTE sudo \"rm --preserve-root=all --recursive --force -- $KW_DEPLOY_TMP_FILE\""
https://kworkflow.org/content/codingstyle.html#string-concatenation

2023-12-17 16:50 UTC, melissawen commented
Hi! Since I have faced similar issue, I tested this PR on remote deployment, it fixes my issue and the kernel with a different name is deployed as expected without rebooting my machine. Feel free to add my tested by tag. Please, use my gmail address :pray:

2024-01-03 17:03 UTC, closed without merging

2024-01-03 17:03 UTC, rodrigosiqueira commented
I made the requested changes and merged this change in the unstable branch. 
Thanks